(()=>{
'use strict';
const $=id=>document.getElementById(id), LS={fav:'teslaWaze:favorites:v1',recent:'teslaWaze:recent:v1',routing:'teslaWaze:routing:v1',voice:'teslaWaze:voice:v1',voiceMode:'teslaWaze:voiceMode:v1',device:'teslaWaze:pairedDevice:v1',alerts:'teslaWaze:alerts:v1',chargeFilter:'teslaWaze:chargeFilter:v1',music:'teslaWaze:musicProfile:v2',queue:'teslaWaze:musicQueue:v2'};
const load=(k,d)=>{try{return JSON.parse(localStorage.getItem(k)||'null')??d}catch{return d}}, save=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v))}catch{}};
const esc=s=>String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const dist=(a,b)=>{const r=Math.PI/180,dlat=(b.lat-a.lat)*r,dlng=(b.lng-a.lng)*r;return 12742000*Math.asin(Math.sqrt(Math.sin(dlat/2)**2+Math.cos(a.lat*r)*Math.cos(b.lat*r)*Math.sin(dlng/2)**2))};
const fmtD=m=>m<1000?`${Math.max(0,Math.round(m/10)*10)} m`:`${(m/1000).toLocaleString('sk-SK',{maximumFractionDigits:1})} km`;
const fmtT=s=>s<3600?`${Math.max(1,Math.round(s/60))} min`:`${Math.floor(s/3600)} h ${Math.round((s%3600)/60)} min`;
const norm=s=>(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,' ').trim();
function bearing(a,b){const p1=a.lat*Math.PI/180,p2=b.lat*Math.PI/180,dl=(b.lng-a.lng)*Math.PI/180;return (Math.atan2(Math.sin(dl)*Math.cos(p2),Math.cos(p1)*Math.sin(p2)-Math.sin(p1)*Math.cos(p2)*Math.cos(dl))*180/Math.PI+360)%360}
function smoothHeading(prev,next,alpha=.24){if(prev==null)return next;let d=((next-prev+540)%360)-180;return (prev+d*alpha+360)%360}
function instruction(step){const op=String(step?.opcode||'').toUpperCase(), street=step?.street?` na ${step.street}`:'';if(op.includes('TURN_RIGHT'))return `OdboÄte doprava${street}.`;if(op.includes('TURN_LEFT'))return `OdboÄte doÄ¾ava${street}.`;if(op.includes('ROUNDABOUT'))return `PokraÄujte cez kruhovÃ½ objazd${street}.`;if(op.includes('DESTINATION'))return 'CieÄ¾ je pred vami.';if(op.includes('KEEP_RIGHT'))return `DrÅ¾te sa vpravo${street}.`;if(op.includes('KEEP_LEFT'))return `DrÅ¾te sa vÄ¾avo${street}.`;return `PokraÄujte rovno${street}.`}
function maneuverIcon(step){const op=String(step?.opcode||'').toUpperCase();if(op.includes('ROUNDABOUT'))return 'â†»';if(op.includes('TURN_RIGHT'))return 'â†±';if(op.includes('TURN_LEFT'))return 'â†°';if(op.includes('KEEP_RIGHT'))return 'â†—';if(op.includes('KEEP_LEFT'))return 'â†–';if(op.includes('DESTINATION'))return 'â—†';return 'â†‘'}
function nearest(p,coords,start=0){if(!coords?.length)return null;let best=null;const cos=111320*Math.cos(p.lat*Math.PI/180);for(let i=Math.max(0,start-20);i<Math.min(coords.length-1,start+600);i++){const a=coords[i],b=coords[i+1],ax=(a.lng-p.lng)*cos,ay=(a.lat-p.lat)*111320,bx=(b.lng-p.lng)*cos,by=(b.lat-p.lat)*111320,dx=bx-ax,dy=by-ay,l=dx*dx+dy*dy,t=l?Math.max(0,Math.min(1,-(ax*dx+ay*dy)/l)):0,d=Math.hypot(ax+t*dx,ay+t*dy);if(!best||d<best.distance)best={index:i,t,distance:d,point:{lat:a.lat+(b.lat-a.lat)*t,lng:a.lng+(b.lng-a.lng)*t}}}return best}
function cumulative(c){const a=[0];for(let i=1;i<c.length;i++)a.push(a[i-1]+dist(c[i-1],c[i]));return a}

const state={pos:null,accuracy:null,speed:null,gpsHeading:null,lastPos:null,heading:null,map:null,L:null,car:null,destMarker:null,routeLines:[],alertMarkers:[],chargerMarkers:[],trafficLines:[],routes:[],routeIndex:0,navigating:false,overview:false,routeCursor:0,routeProgress:null,dest:null,alerts:[],alertsOn:load(LS.alerts,true),jams:[],chargers:[],chargersOn:false,chargeFilter:load(LS.chargeFilter,'all'),routing:{useVignette:true,avoidTolls:false,avoidFerries:false,...load(LS.routing,{})},voice:load(LS.voice,true),voiceMode:load(LS.voiceMode,'soft'),favorites:load(LS.fav,[]),recents:load(LS.recent,[]),panelHidden:false,lastVoice:'',lastReroute:0,offRouteHits:0,overviewTimer:null,searchHome:null};

function renderPlaces(){const fav=$('favorites'),rec=$('recents');$('favCount').textContent=state.favorites.length;$('recentCount').textContent=state.recents.length;fav.innerHTML=state.favorites.length?state.favorites.map(x=>`<button class="result" data-place="fav:${esc(x.id)}"><b>${esc(x.name)}</b><small>${esc(x.address)}</small></button>`).join(''):'<small>ZatiaÄ¾ bez uloÅ¾enÃ½ch miest.</small>';rec.innerHTML=state.recents.length?state.recents.slice(0,10).map(x=>`<button class="result" data-place="rec:${esc(x.id)}"><b>${esc(x.name)}</b><small>${esc(x.address)}</small></button>`).join(''):'<small>HistÃ³ria je prÃ¡zdna.</small>';document.querySelectorAll('[data-place]').forEach(b=>b.onclick=()=>{const [kind,id]=b.dataset.place.split(':');const a=kind==='fav'?state.favorites:state.recents;const x=a.find(z=>String(z.id)===id);if(x)selectDestination(x)});const home=state.favorites.find(x=>x.kind==='home'),work=state.favorites.find(x=>x.kind==='work');$('homeBtn').disabled=!home;$('workBtn').disabled=!work;$('homeBtn').onclick=()=>home&&selectDestination(home);$('workBtn').onclick=()=>work&&selectDestination(work)}
function routingStatus(){ $('routingStatus').textContent=state.routing.avoidTolls?'bez mÃ½ta':state.routing.useVignette?'znÃ¡mka zap.':'Å¡tandard'; }
function showPanel(show=true){state.panelHidden=!show;$('app').classList.toggle('panel-off',!show);$('panel').classList.toggle('hidden',!show);$('panelBtn').textContent=show?'SkryÅ¥ panel':'Panel';setTimeout(()=>state.map?.invalidateSize(),100)}

async function initMap(){const L=window.L;state.L=L;state.map=L.map('map',{zoomControl:true,attributionControl:true,rotate:true,bearing:0,rotateControl:false,dragRotate:false,touchRotate:false,shiftKeyRotate:false}).setView([48.9984,21.2393],12);L.tileLayer('https://www.waze.com/row-tiles/live/base/{z}/{x}/{y}/tile.png',{maxZoom:20,attribution:'Waze'}).addTo(state.map);startGPS();setInterval(loadAlerts,30000);setTimeout(loadAlerts,2200)}
function carIcon(){return state.L.divIcon({className:'car-wrap',html:'<div class="car-arrow">â–²</div>',iconSize:[40,40],iconAnchor:[20,20]})}
function startGPS(){if(!navigator.geolocation){$('gpsNotice').querySelector('span').textContent='GPS nie je dostupnÃ©.';return}let lastTs=Date.now(),watch;const restart=()=>{if(watch)navigator.geolocation.clearWatch(watch);watch=navigator.geolocation.watchPosition(g=>{lastTs=Date.now();const p={lat:g.coords.latitude,lng:g.coords.longitude}, sp=Number.isFinite(g.coords.speed)?g.coords.speed:null, raw=Number.isFinite(g.coords.heading)?g.coords.heading:null;let h=raw;if((h==null||sp!=null&&sp<.8)&&state.lastPos&&dist(state.lastPos,p)>4)h=bearing(state.lastPos,p);if(h!=null)state.heading=smoothHeading(state.heading,h);state.lastPos=state.pos||p;state.pos=p;state.accuracy=g.coords.accuracy;state.speed=sp;state.gpsHeading=raw;$('speed').textContent=`${sp==null?'â€”':Math.max(0,Math.round(sp*3.6))} km/h`;$('gpsNotice').querySelector('span').textContent=`GPS aktÃ­vne Â· presnosÅ¥ pribliÅ¾ne ${Math.round(g.coords.accuracy)} m`;if(state.car)state.car.setLatLng(p);else{state.car=state.L.marker(p,{icon:carIcon(),zIndexOffset:1000,rotation:0,rotateWithView:false}).addTo(state.map);state.map.setView(p,16)}if(state.navigating)updateNavigation();},e=>$('gpsNotice').querySelector('span').textContent=e.code===1?'Poloha bola zamietnutÃ¡.':'GPS momentÃ¡lne nie je dostupnÃ©.',{enableHighAccuracy:true,timeout:12000,maximumAge:0})};restart();setInterval(()=>{if(Date.now()-lastTs>10000){$('gpsNotice').querySelector('span').textContent='GPS neposiela novÃº polohu. Obnovujem sledovanie.';restart()}},3000)}
function applyHead²È="25µÕÍ¥Œ¹Í¡Õ™™±”˜™Ä¹±•¹Ñ øÄ¥í½¹ÍĞÕÈõµÕÍ¥Œ¹ÕÉÉ•¹ĞıµĞ¡µÕÍ¥Œ¹ÕÉÉ•¹Ğ¤¹¥èœœí½¹ÍĞ…¹‘¥‘…Ñ•ÌõÄ¹™¥±Ñ•È¡àôùµĞ¡à¤¹¥„ôõÕÈ¤í¸õ…¹‘¥‘…Ñ•Ím5…Ñ ¹™±½½È¡5…Ñ ¹É…¹‘½´ ¤©…¹‘¥‘…Ñ•Ì¹±•¹Ñ ¥uõ•±Í•í½¹ÍĞ¤õÄ¹™¥¹‘%¹‘•à¡àôùµÕÍ¥Œ¹ÕÉÉ•¹Ğ˜™µĞ¡à¤¹¥ôôõµĞ¡µÕÍ¥Œ¹ÕÉÉ•¹Ğ¤¹¥¤í¸õÅl¡¤¬Ä­Ä¹±•¹Ñ ¤•Ä¹±•¹Ñ¡uõ¥˜¡¸¥µÁ±…ä¡¸¥¶»§q«^