from pathlib import Path
import re,gzip,base64
p=Path('tesla-waze-preview/app.js')
s=p.read_text()
s,n=re.subn(r"function syncTwMusicEngineVisibility\(\)\{.*?\n\}","function syncTwMusicEngineVisibility(){}/* MUSIC_ENGINE_DISABLED_V122 */",s,count=1,flags=re.S)
assert n==1,('visibility',n)
s,n=re.subn(r"async function switchYoutubeToFree\(yt,manual=false\)\{.*?\}\n", "async function switchYoutubeToFree(yt,manual=false){if(!yt)return;music.anonymousYoutube=true;music.fallbackAttempts=0;if(music.fallbackTimer){clearTimeout(music.fallbackTimer);music.fallbackTimer=null}setYoutubeFallbackStatus(manual?'Spúšťam bezplatné YouTube s reklamami…':'YouTube účet je blokovaný · prepínam na prehrávanie s reklamami…',true);try{music.ytPlayer?.destroy?.()}catch{}music.ytPlayer=null;const host=document.getElementById('ytPlayerHost');if(host){host.innerHTML=''}await setupYoutubePlayer(yt,true)}\n", s,count=1,flags=re.S)
assert n==1,('switch',n)
start=s.index('async function setupYoutubePlayer(yt,anonymous=music.anonymousYoutube){')
end_marker='/* MUSIC_ISOLATED_WATCHDOG_V110 */'
end=s.index(end_marker,start)+len(end_marker)
direct="""async function setupYoutubePlayer(yt,anonymous=music.anonymousYoutube){try{await loadYoutubeApi();const host=document.getElementById('ytPlayerHost');if(!host)return;music.anonymousYoutube=!!anonymous;try{music.ytPlayer?.destroy?.()}catch{}host.innerHTML='';setYoutubeFallbackStatus(anonymous?'Free YouTube · reklamy môžu byť zobrazené':'YouTube účet',anonymous);music.ytPlayer=new YT.Player('ytPlayerHost',{host:anonymous?'https://www.youtube-nocookie.com':'https://www.youtube.com',videoId:yt,playerVars:{autoplay:1,playsinline:1,rel:0,origin:location.origin},events:{onReady:e=>{syncMediaSession();try{e.target.playVideo()}catch{}},onStateChange:e=>{if(e.data===YT.PlayerState.PLAYING){music.fallbackAttempts=0;music.wantsPlayback=true;if(!music.playingSince)music.playingSince=Date.now();setMusicPlaying(true);setTimeout(()=>{try{const d=Number(e.target?.getDuration?.()||0);if(d>0&&d<MUSIC_MIN_SECONDS){if(invalidateCurrentMedia('short-youtube',d)){try{e.target.pauseVideo?.()}catch{};mnext('auto');return}}if(d>0&&music.current){const st=mt(music.current);st.durationSeconds=Math.round(d);save(LS.music,music.profile)}}catch{}},650);if(music.manualNavPending){if(music.manualNavTimer)clearTimeout(music.manualNavTimer);music.manualNavTimer=setTimeout(()=>{music.manualNavTimer=null;drainManualMusicNav()},1500)}}else if(e.data===YT.PlayerState.PAUSED){if(music.userPaused||!music.wantsPlayback)setMusicPlaying(false);else{setMusicPlaying(true);scheduleMusicResume();noteYoutubeBlockedState(yt)}}else if(e.data===YT.PlayerState.CUED||e.data===YT.PlayerState.UNSTARTED){if(music.userPaused||!music.wantsPlayback)setMusicPlaying(false);else setMusicPlaying(true)}/* MUSIC_YT_STARTUP_STABLE_V91 */else if(e.data===YT.PlayerState.ENDED){if(Date.now()<(music.suppressEndedUntil||0))return;if(music.current)mev('complete',music.current);if(music.autoNext&&!music.userPaused){music.wantsPlayback=true;setMusicPlaying(true);mnext('auto')}else{music.wantsPlayback=false;setMusicPlaying(false)}}},onError:()=>{if(!anonymous&&music.wantsPlayback&&!music.userPaused)noteYoutubeBlockedState(yt)}}})}catch{const h=document.getElementById('ytPlayerHost');if(h){const base=anonymous?'https://www.youtube-nocookie.com':'https://www.youtube.com';h.innerHTML=`<iframe class=\"yt-player\" src=\"${base}/embed/${encodeURIComponent(yt)}?autoplay=1&playsinline=1\" allow=\"autoplay; encrypted-media; picture-in-picture\" allowfullscreen></iframe>`;setYoutubeFallbackStatus(anonymous?'Free YouTube · reklamy môžu byť zobrazené':'YouTube účet',anonymous)}syncMediaSession()}}
setInterval(()=>{if(music.anonymousYoutube||music.userPaused||!music.wantsPlayback||!music.ytPlayer)return;try{const st=music.ytPlayer.getPlayerState?.();if(st!==YT.PlayerState.PLAYING&&st!==YT.PlayerState.BUFFERING)setYoutubeFallbackStatus('YouTube čaká · ak nehrá, použi S reklamami',true)}catch{}},2600);/* MUSIC_DIRECT_PLAYER_V122 */"""
s=s[:start]+direct+s[end:]
assert 'ensureTwMusicEngine();music.anonymousYoutube=true;music.ytPlayer=makeTwMusicProxy()' not in s
p.write_text(s)
b=base64.b64encode(gzip.compress(p.read_bytes(),compresslevel=9,mtime=0)).decode()
Path('tesla-waze-preview/app.js.gz.b64').write_text(b)
assert gzip.decompress(base64.b64decode(b))==p.read_bytes()
