const PK='teslaMusic:brain:v1',QK='teslaMusic:queue:v1',HK='teslaMusic:searchHistory:v1',SK='teslaMusic:settings:v1',WK='teslaMusic:window:v2';
const $=id=>document.getElementById(id);
const load=(k,d)=>{try{return JSON.parse(localStorage.getItem(k)||'null')??d}catch{return d}};
const save=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v))}catch{}};
let profile=load(PK,{tracks:{},artists:{},events:[]}),queue=load(QK,[]),settings=load(SK,{shuffle:false,auto:true}),items=[],idx=-1,player=null,ready=false,current=null,started=0,relatedBusy=false,tab='foryou';
const fmt=v=>{v=Number(v)||0;const m=Math.floor(v/60),s=Math.floor(v%60);return m+':'+String(s).padStart(2,'0')};
const key=t=>'yt:'+String(t?.id||t?.youtubeId||'');
const esc=s=>String(s||'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[m]));
function isAutoMusic(t){
  if(!t)return false;
  const title=String(t.title||'').toLowerCase(),artist=String(t.uploader||t.artist||'').toLowerCase(),d=Number(t.duration||0);
  const reject=/(podcast|rozhovor|interview|trailer|full movie|movie|film|dokument|documentary|správy|news|tutorial|návod|navod|review|recenzia|unboxing|vlog|gameplay|walkthrough|press conference|tlačová konferencia|talk show|full episode|episode|epizóda|epizoda|audiobook|prednáška|prednaska|livestream|live stream)/i;
  if(reject.test(title+' '+artist))return false;
  const strong=/( - topic\b|topic$|official audio|official music video|music video|lyric|lyrics|remix|\bmix\b|\bsong\b|\bmusic\b|\bhudba\b|karaoke|album|\bdj\b|dance|feat\.?|ft\.?)/i.test(title+' '+artist);
  if(d>0&&d<45)return false;
  if(d>=75&&d<=900)return true;
  if(d>900&&d<=14400)return strong;
  return strong;
}
function tr(t){const k=key(t);if(k==='yt:')return null;let o=profile.tracks[k];if(o){o.title=t.title||o.title;o.artist=t.uploader||t.artist||o.artist;o.duration=Number(t.duration||o.duration||0);o.thumbnail=t.thumbnail||o.thumbnail;return o}return profile.tracks[k]={id:k,youtubeId:String(t.id||t.youtubeId||''),title:t.title||'',artist:t.uploader||t.artist||'YouTube',duration:Number(t.duration||0),thumbnail:t.thumbnail||'',score:0,plays:0,completed:0,skips:0,liked:false,lastPlayed:null}}
function ar(n){const k=String(n||'YouTube').toLowerCase();return profile.artists[k]||(profile.artists[k]={name:n||'YouTube',score:0,plays:0})}
function ev(type,t){const s=tr(t);if(!s)return;const a=ar(s.artist),d={like:5,unlike:-5,complete:3,play:.4,skip:-1.5,replay:2}[type]||0;s.score+=d;a.score+=d*.7;if(type==='play'){s.plays++;a.plays++;s.lastPlayed=new Date().toISOString()}if(type==='complete')s.completed++;if(type==='skip')s.skips++;if(type==='like')s.liked=true;if(type==='unlike')s.liked=false;profile.events.push({type,id:s.id,at:new Date().toISOString()});profile.events=profile.events.slice(-500);save(PK,profile);stats()}
function item(s){return{id:s.youtubeId,title:s.title,uploader:s.artist,duration:s.duration,thumbnail:s.thumbnail}}
function score(s){return(s.score||0)+(s.liked?5:0)+(s.plays||0)*.6+(s.completed||0)*.8-(s.skips||0)*.5+(ar(s.artist).score||0)*.3}
function rows(){const a=Object.values(profile.tracks);if(tab==='likes')return a.filter(x=>x.liked).sort((a,b)=>score(b)-score(a)).map(item);if(tab==='recent')return a.filter(x=>x.lastPlayed).sort((a,b)=>Date.parse(b.lastPlayed)-Date.parse(a.lastPlayed)).map(item);if(tab==='queue')return queue;const l=[...a].sort((a,b)=>score(b)-score(a)).map(item),seen=new Set(l.map(key));return[...l,...queue.filter(x=>!seen.has(key(x)))].slice(0,80)}
function render(list=rows()){items=list;$('sectionTitle').textContent={foryou:'Pre teba',likes:'Obľúbené',recent:'Naposledy prehrané',queue:'Poradie'}[tab];$('grid').innerHTML=list.length?list.map((x,i)=>{const s=tr(x);return `<div class="card" data-i="${i}"><div class="thumb-wrap"><img class="thumb" src="${esc(x.thumbnail)}"><span class="duration">${fmt(x.duration)}</span></div><div class="card-body"><div><div class="ctitle">${esc(x.title)}</div><div class="meta">${esc(x.uploader||'YouTube')}</div></div><button class="heart ${s?.liked?'on':''}" data-like="${i}">${s?.liked?'♥':'♡'}</button></div></div>`}).join(''):'<div class="empty">Zatiaľ nič. Vyhľadaj a prehraj niekoľko skladieb.</div>';$('grid').querySelectorAll('[data-i]').forEach(c=>c.onclick=e=>{if(e.target.closest('[data-like]'))return;playTrack(items[+c.dataset.i])});$('grid').querySelectorAll('[data-like]').forEach(b=>b.onclick=e=>{e.stopPropagation();like(items[+b.dataset.like]);render(items)})}
function stats(){const a=Object.values(profile.tracks);$('learned').textContent=a.length+' naučených';$('plays').textContent=a.reduce((n,x)=>n+(x.plays||0),0)+' prehratí';$('likesCount').textContent=a.filter(x=>x.liked).length+' obľúbených'}
function remember(q){const h=[q,...load(HK,[]).filter(x=>String(x).toLowerCase()!==q.toLowerCase())].slice(0,10);save(HK,h);hist()}
function hist(){const h=load(HK,[]);$('history').classList.toggle('show',h.length>0);$('history').innerHTML=h.map(q=>`<button data-h="${esc(q)}">${esc(q)}</button>`).join('');$('history').querySelectorAll('[data-h]').forEach(b=>b.onclick=()=>{$('q').value=b.dataset.h;search()})}
async function search(){const q=$('q').value.trim();if(!q)return;remember(q);$('status').textContent='Hľadám…';try{const r=await fetch('https://dimvegkezslqjtsxdohp.supabase.co/functions/v1/twyoutubesearch?q='+encodeURIComponent(q),{cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(d.error||r.status);const out=(d.items||[]).map(x=>({id:x.youtubeId||String(x.id||'').replace(/^youtube:/,''),title:x.title||'',uploader:x.artist||'YouTube',duration:Number(x.duration||0),thumbnail:x.artwork||''})).filter(x=>x.id&&x.title).map(x=>{tr(x);return x});queue=out;save(QK,queue);tab='queue';tabs();render(out);$('status').textContent=out.length+' výsledkov'}catch(e){$('status').textContent='Search chyba: '+e.message}}
function tabs(){document.querySelectorAll('[data-tab]').forEach(b=>{b.classList.toggle('active',b.dataset.tab===tab);if(b.dataset.tab==='queue')b.textContent='Poradie'})}
function like(t){const s=tr(t);if(!s)return;ev(s.liked?'unlike':'like',t);now();if(tab==='likes')render()}
function playTrack(t){if(!t||!ready)return;if(current&&started&&Date.now()-started<15000&&key(current)!==key(t))ev('skip',current);const replay=current&&key(current)===key(t);current=t;let q=queue.findIndex(x=>key(x)===key(t));if(q<0){queue.unshift(t);q=0;save(QK,queue)}idx=q;ev(replay?'replay':'play',t);started=Date.now();$('now').textContent=t.title;$('sub').textContent=(t.uploader||'YouTube')+' · '+fmt(t.duration);$('pcurrent').textContent=t.title;$('bname').textContent=t.title;$('bmeta').textContent=t.uploader||'YouTube';player.loadVideoById(t.id);now();discover(t);media();window.dispatchEvent(new CustomEvent('tesla-music-trackchange',{detail:t}))}
window.playTrack=playTrack;
function next(man=true){if(!queue.length)return;if(current&&man&&started&&Date.now()-started<15000)ev('skip',current);const start=Math.max(-1,idx);let chosen=-1;if(settings.shuffle&&queue.length>1){const candidates=queue.map((x,i)=>({x,i})).filter(o=>isAutoMusic(o.x)&&(!current||key(o.x)!==key(current)));if(candidates.length)chosen=candidates[Math.floor(Math.random()*candidates.length)].i}else{for(let step=1;step<=queue.length;step++){const i=(start+step)%queue.length;if(isAutoMusic(queue[i])){chosen=i;break}}}if(chosen<0)chosen=(start+1)%queue.length;idx=chosen;playTrack(queue[idx])}
function prev(){if(!queue.length)return;idx=(idx<=0?queue.length:idx)-1;playTrack(queue[idx])}
function now(){if(!current)return;const s=tr(current);$('like').textContent=s?.liked?'♥':'♡';$('like').classList.toggle('on',!!s?.liked);stats()}
async function discover(t){if(relatedBusy)return;relatedBusy=true;try{const qs=[(t.uploader||'')+' songs',(t.uploader||'')+' '+(t.title||'')+' similar songs'];const bs=await Promise.allSettled(qs.map(q=>fetch('https://dimvegkezslqjtsxdohp.supabase.co/functions/v1/twyoutubesearch?q='+encodeURIComponent(q),{cache:'no-store'}).then(async r=>{if(!r.ok)return{items:[]};const d=await r.json();return{items:(d.items||[]).map(x=>({id:x.youtubeId||String(x.id||'').replace(/^youtube:/,''),title:x.title||'',uploader:x.artist||'YouTube',duration:Number(x.duration||0),thumbnail:x.artwork||''})).filter(x=>x.id&&x.title&&isAutoMusic(x))}})));const seen=new Set(queue.map(key));let a=0;for(const b of bs){if(b.status!=='fulfilled')continue;for(const x of b.value.items||[]){tr(x);if(!seen.has(key(x))){queue.push(x);seen.add(key(x));if(++a>=18)break}}if(a>=18)break}save(QK,queue);if(tab==='foryou'||tab==='queue')render()}catch{}finally{relatedBusy=false}}
function toggle(){if(!player||!ready)return;player.getPlayerState()===1?player.pauseVideo():player.playVideo()}
function tick(){if(!player||!ready)return;try{const c=player.getCurrentTime()||0,d=player.getDuration()||0;$('seek').value=d?Math.round(c/d*1000):0;$('btime').textContent=fmt(c)+' / '+fmt(d);const p=player.getPlayerState()===1;$('play').textContent=$('bplay').textContent=p?'⏸':'▶';window.dispatchEvent(new CustomEvent('tesla-music-tick',{detail:{playing:p,now:c,duration:d}}))}catch{}}
function media(){if(!current)return;try{if('mediaSession'in navigator){navigator.mediaSession.metadata=new MediaMetadata({title:current.title,artist:current.uploader||'YouTube',album:'Tesla Music'});navigator.mediaSession.playbackState=player?.getPlayerState?.()===1?'playing':'paused'}}catch{}}
window.onYouTubeIframeAPIReady=()=>{player=new YT.Player('yt',{width:'100%',height:'100%',playerVars:{playsinline:1,autoplay:0,controls:1,rel:0,fs:0,iv_load_policy:3,modestbranding:1},events:{onReady:()=>{ready=true;$('status').textContent='YouTube player pripravený';setInterval(tick,500);tabs();render();stats()},onStateChange:e=>{if(e.data===YT.PlayerState.ENDED){if(current)ev('complete',current);if(settings.auto)next(false)}media()},onError:e=>$('status').textContent='YouTube player chyba: '+e.data}})};
$('go').onclick=search;$('q').onkeydown=e=>{if(e.key==='Enter')search()};$('prev').onclick=$('bprev').onclick=prev;$('next').onclick=$('bnext').onclick=()=>next(true);$('play').onclick=$('bplay').onclick=toggle;$('like').onclick=()=>current&&like(current);$('shuffle').onclick=()=>{settings.shuffle=!settings.shuffle;save(SK,settings);$('shuffle').classList.toggle('active',settings.shuffle)};$('auto').onclick=()=>{settings.auto=!settings.auto;save(SK,settings);$('auto').classList.toggle('active',settings.auto)};$('seek').onchange=()=>{if(player&&ready){const d=player.getDuration()||0;player.seekTo(+$('seek').value/1000*d,true)}};document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;tabs();render()});
try{if('mediaSession'in navigator){navigator.mediaSession.setActionHandler('play',()=>player?.playVideo());navigator.mediaSession.setActionHandler('pause',()=>player?.pauseVideo());navigator.mediaSession.setActionHandler('nexttrack',()=>next(true));navigator.mediaSession.setActionHandler('previoustrack',prev);navigator.mediaSession.setActionHandler('seekto',d=>{if(player&&Number.isFinite(d.seekTime))player.seekTo(d.seekTime,true)})}}catch{}
let ws=load(WK,{x:null,y:110,w:720,h:610,min:false,max:false}),drag=null,rs=null;const pw=$('playerWindow');
function clamp(){if(innerWidth<=760)return;ws.w=Math.max(420,Math.min(innerWidth-16,ws.w||720));ws.h=Math.max(360,Math.min(innerHeight-110,ws.h||610));if(ws.x==null)ws.x=Math.max(8,innerWidth-ws.w-18);ws.x=Math.max(8,Math.min(innerWidth-ws.w-8,ws.x));ws.y=Math.max(82,Math.min(innerHeight-ws.h-92,ws.y||110))}
function apply(){clamp();pw.classList.toggle('minimized',!!ws.min);pw.classList.toggle('max',!!ws.max);if(innerWidth>760&&!ws.max){pw.style.left=ws.x+'px';pw.style.top=ws.y+'px';pw.style.width=ws.w+'px';pw.style.height=ws.h+'px'}$('pmax').textContent=ws.max?'↙':'□';save(WK,ws)}
$('pmin').onclick=()=>{ws.min=true;apply()};$('restore').onclick=$('binfo').onclick=()=>{ws.min=false;apply()};$('pmax').onclick=()=>{ws.max=!ws.max;ws.min=false;apply()};
$('phead').addEventListener('pointerdown',e=>{if(innerWidth<=760||e.target.closest('button')||ws.max)return;drag={id:e.pointerId,x:e.clientX,y:e.clientY,ox:ws.x,oy:ws.y};$('phead').setPointerCapture?.(e.pointerId)});$('phead').addEventListener('pointermove',e=>{if(!drag||drag.id!==e.pointerId)return;ws.x=drag.ox+e.clientX-drag.x;ws.y=drag.oy+e.clientY-drag.y;apply()});$('phead').addEventListener('pointerup',e=>{if(drag?.id===e.pointerId)drag=null});
$('resize').addEventListener('pointerdown',e=>{if(innerWidth<=760||ws.max)return;rs={id:e.pointerId,x:e.clientX,y:e.clientY,w:ws.w,h:ws.h};$('resize').setPointerCapture?.(e.pointerId);e.preventDefault()});$('resize').addEventListener('pointermove',e=>{if(!rs||rs.id!==e.pointerId)return;ws.w=rs.w+e.clientX-rs.x;ws.h=rs.h+e.clientY-rs.y;apply()});$('resize').addEventListener('pointerup',e=>{if(rs?.id===e.pointerId)rs=null});addEventListener('resize',apply);
$('shuffle').classList.toggle('active',settings.shuffle);$('auto').classList.toggle('active',settings.auto);hist();tabs();stats();render();apply();