(()=>{
  const qs=new URLSearchParams(location.search),MAP=qs.get('map')==='1',EMBED=qs.get('embed')==='1';
  const pw=document.getElementById('playerWindow'),head=document.getElementById('phead'),pmin=document.getElementById('pmin'),pmax=document.getElementById('pmax'),corner=document.getElementById('miniResizeCorner');
  if(!pw||!head)return;
  if(EMBED)document.body.classList.add('music-embed');
  const ORIGIN='https://tesla-waze.vercel.app',FULL_SIZE_KEY='teslaMusic:fullPlayerSize:v1';
  let videoOn=MAP?false:(sessionStorage.getItem('teslaMusic:videoVisible:v1')==='1');
  let drag=null,resize=null,lastSent='';
  const read=(k,d)=>{try{return JSON.parse(localStorage.getItem(k)||'null')??d}catch{return d}},write=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v))}catch{}};
  let fullSize=read(FULL_SIZE_KEY,{w:720,h:610});
  function isMini(){return pw.classList.contains('mini-recs')}
  function localizeLabels(){const q=document.querySelector('[data-tab="queue"]');if(q&&q.textContent!=='Poradie')q.textContent='Poradie';const s=document.getElementById('sectionTitle');if(s&&s.textContent==='Queue')s.textContent='Poradie'}
  const originalRender=typeof window.render==='function'?window.render:null;if(originalRender)window.render=function(...args){const r=originalRender.apply(this,args);localizeLabels();return r};
  localizeLabels();document.querySelector('[data-tab="queue"]')?.addEventListener('click',()=>setTimeout(localizeLabels,0));
  function ensureVideoButton(){if(document.getElementById('videoToggle'))return document.getElementById('videoToggle');const b=document.createElement('button');b.id='videoToggle';b.className='video-toggle';b.type='button';head.insertBefore(b,pmin||pmax||null);b.onclick=e=>{e.preventDefault();e.stopPropagation();if(isMini())return;videoOn=!videoOn;sessionStorage.setItem('teslaMusic:videoVisible:v1',videoOn?'1':'0');syncUi(true)};return b}
  function ensureCloseButton(){if(!EMBED)return null;if(document.getElementById('musicClose'))return document.getElementById('musicClose');const b=document.createElement('button');b.id='musicClose';b.className='iconbtn';b.type='button';b.textContent='×';b.title='Zavrieť hudbu';b.style.fontSize='25px';head.appendChild(b);b.onclick=e=>{e.preventDefault();e.stopPropagation();videoOn=false;applyVideo();try{parent.postMessage({type:'tesla-music-close'},ORIGIN)}catch{}};return b}
  function clampFullSize(w,h){const maxW=Math.max(420,innerWidth-36),maxH=Math.max(360,innerHeight-120);return{w:Math.max(420,Math.min(maxW,Number(w)||720)),h:Math.max(360,Math.min(maxH,Number(h)||610))}}
  function applyFullSize(){if(!EMBED||isMini())return;fullSize=clampFullSize(fullSize.w,fullSize.h);write(FULL_SIZE_KEY,fullSize);pw.style.setProperty('left','auto','important');pw.style.setProperty('right','18px','important');pw.style.setProperty('top','auto','important');pw.style.setProperty('bottom','96px','important');pw.style.setProperty('width',fullSize.w+'px','important');pw.style.setProperty('height',fullSize.h+'px','important')}
  function applyVideo(){if(isMini())videoOn=false;const off=!videoOn;if(pw.classList.contains('video-off')!==off)pw.classList.toggle('video-off',off);const b=ensureVideoButton();const txt=videoOn?'🎵 Hudba':'🎬 Video';if(b.textContent!==txt)b.textContent=txt;b.title=videoOn?'Skryť video a nechať hudobné ovládanie':'Zobraziť video';b.style.display=isMini()?'none':'';if(MAP&&!videoOn)sessionStorage.removeItem('teslaMusic:videoVisible:v1')}
  function applyMode(){const mini=isMini();document.body.classList.toggle('music-full',EMBED&&!mini);if(EMBED&&mini){const s=pw.style;pw.classList.remove('max');if(s.getPropertyValue('left')!=='0px')s.setProperty('left','0px','important');if(s.getPropertyValue('top')!=='0px')s.setProperty('top','0px','important');if(s.getPropertyValue('width')!=='100%')s.setProperty('width','100%','important');if(s.getPropertyValue('height')!=='100%')s.setProperty('height','100%','important');s.removeProperty('right');s.removeProperty('bottom')}else if(EMBED&&!mini){pw.classList.remove('max');applyFullSize()}localizeLabels()}
  function notify(force=false){if(!EMBED||window.parent===window)return;const payload={type:'tesla-music-ui-state',mode:isMini()?'mini':'full',video:videoOn},sig=payload.mode+'|'+payload.video;if(!force&&sig===lastSent)return;lastSent=sig;try{parent.postMessage(payload,ORIGIN)}catch{}}
  function syncUi(force=false){applyMode();applyVideo();notify(force)}
  function startup(){if(MAP&&typeof window.teslaMusicSetMini==='function')window.teslaMusicSetMini();if(MAP)videoOn=false;ensureCloseButton();ensureVideoButton();syncUi(true)}
  setTimeout(startup,0);setTimeout(startup,350);
  window.teslaMusicSetVideo=v=>{videoOn=!!v;if(isMini())videoOn=false;sessionStorage.setItem('teslaMusic:videoVisible:v1',videoOn?'1':'0');syncUi(true)};
  window.teslaMusicToggleVideo=()=>{if(!isMini())window.teslaMusicSetVideo(!videoOn)};
  window.addEventListener('message',e=>{if(e.origin!==ORIGIN||!e.data||e.data.type!=='tesla-music-command')return;const a=e.data.action;if(a==='mini')window.teslaMusicSetMini?.();else if(a==='full')window.teslaMusicSetFull?.();else if(a==='video-toggle')window.teslaMusicToggleVideo?.();else if(a==='video-off')videoOn=false;else if(a==='video-on'&&!isMini())videoOn=true;setTimeout(()=>syncUi(true),0)});
  if(EMBED&&pmax){pmax.onclick=e=>{e.preventDefault();e.stopPropagation();if(isMini())window.teslaMusicSetFull?.();else window.teslaMusicSetMini?.();setTimeout(()=>syncUi(true),0)}}
  if(pmin)pmin.addEventListener('click',()=>setTimeout(()=>syncUi(true),0),false);
  if(EMBED){
    head.addEventListener('pointerdown',e=>{if(!isMini()||e.target.closest('button,input')||e.button!==0)return;e.preventDefault();e.stopImmediatePropagation();drag={id:e.pointerId,x:e.clientX,y:e.clientY};head.setPointerCapture?.(e.pointerId)},true);
    head.addEventListener('pointermove',e=>{if(!drag||drag.id!==e.pointerId)return;e.preventDefault();e.stopImmediatePropagation();const dx=e.clientX-drag.x,dy=e.clientY-drag.y;drag.x=e.clientX;drag.y=e.clientY;try{parent.postMessage({type:'tesla-music-move',dx,dy},ORIGIN)}catch{}},true);
    head.addEventListener('pointerup',e=>{if(!drag||drag.id!==e.pointerId)return;e.preventDefault();e.stopImmediatePropagation();drag=null},true);
    if(corner){corner.addEventListener('pointerdown',e=>{e.preventDefault();e.stopImmediatePropagation();const r=pw.getBoundingClientRect();resize={id:e.pointerId,x:e.clientX,y:e.clientY,w:r.width,h:r.height,mini:isMini()};corner.setPointerCapture?.(e.pointerId)},true);corner.addEventListener('pointermove',e=>{if(!resize||resize.id!==e.pointerId)return;e.preventDefault();e.stopImmediatePropagation();const dx=e.clientX-resize.x,dy=e.clientY-resize.y;if(resize.mini){resize.x=e.clientX;resize.y=e.clientY;try{parent.postMessage({type:'tesla-music-resize',anchor:'tl',dx,dy},ORIGIN)}catch{}}else{fullSize=clampFullSize(resize.w-dx,resize.h-dy);applyFullSize()}},true);corner.addEventListener('pointerup',e=>{if(!resize||resize.id!==e.pointerId)return;e.preventDefault();e.stopImmediatePropagation();if(!resize.mini)write(FULL_SIZE_KEY,fullSize);resize=null},true);corner.addEventListener('pointercancel',e=>{if(resize?.id===e.pointerId){if(!resize.mini)write(FULL_SIZE_KEY,fullSize);resize=null}},true)}
  }
  addEventListener('resize',()=>{if(!isMini())applyFullSize()});
  ensureCloseButton();ensureVideoButton();syncUi(true);
})();