(()=>{
'use strict';
if(window.__TESLA_OFFLINE_V20__)return;window.__TESLA_OFFLINE_V20__=true;
const st=document.createElement('style');st.textContent=`
.offline-tools{grid-column:1/-1;display:flex;align-items:center;gap:12px;flex-wrap:wrap;margin-bottom:4px}.offline-add{min-width:170px}.offline-summary{color:var(--muted);font-size:14px}.offline-card{grid-column:1/-1;display:grid;grid-template-columns:54px minmax(0,1fr) 48px;align-items:center;gap:10px;background:var(--panel);border:1px solid var(--line);border-radius:14px;padding:9px 10px;cursor:pointer;min-height:70px}.offline-note{width:50px;height:50px;border-radius:12px;background:var(--panel2);display:flex;align-items:center;justify-content:center;font-size:26px}.offline-info{min-width:0}.offline-info .ctitle{white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.offline-delete{width:44px;height:44px;border:1px solid var(--line);border-radius:12px;background:var(--panel2);color:var(--text);font-size:26px}.offline-empty{grid-column:1/-1}.offline-empty small{display:block;margin-top:8px;line-height:1.4}.offline-mode .video{visibility:hidden}.offline-mode #like,.offline-mode #shuffle,.offline-mode #auto{visibility:hidden}
@media(max-width:600px){.offline-tools{display:grid;grid-template-columns:1fr;gap:8px}.offline-add{width:100%;height:50px}.offline-summary{font-size:12px;padding:0 2px}.offline-card{grid-template-columns:48px minmax(0,1fr) 44px;min-height:66px;padding:8px}.offline-note{width:44px;height:44px;font-size:23px}.offline-info .ctitle{font-size:15px}.offline-info .meta{font-size:12px}.offline-delete{width:40px;height:40px}.offline-mode .content{padding-bottom:calc(108px + env(safe-area-inset-bottom))!important}}
`;document.head.appendChild(st);
const DB='teslaMusicOfflineV1',STORE='tracks';
let db=null,offlineMode=false,list=[],currentIndex=-1,currentRec=null,currentUrl='';
const audio=new Audio();audio.preload='metadata';audio.setAttribute('playsinline','');document.body.appendChild(audio);audio.style.display='none';
const $=id=>document.getElementById(id),fmt=v=>{v=Math.max(0,Math.floor(Number(v)||0));return Math.floor(v/60)+':'+String(v%60).padStart(2,'0')};
const esc=s=>String(s||'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[m]));
function openDB(){return new Promise((res,rej)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>{const d=r.result;if(!d.objectStoreNames.contains(STORE))d.createObjectStore(STORE,{keyPath:'id'})};r.onsuccess=()=>{db=r.result;res(db)};r.onerror=()=>rej(r.error)})}
function tx(mode='readonly'){return db.transaction(STORE,mode).objectStore(STORE)}
function all(){return new Promise((res,rej)=>{const r=tx().getAll();r.onsuccess=()=>res((r.result||[]).sort((a,b)=>(b.addedAt||0)-(a.addedAt||0)));r.onerror=()=>rej(r.error)})}
function put(x){return new Promise((res,rej)=>{const r=tx('readwrite').put(x);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}
function del(id){return new Promise((res,rej)=>{const r=tx('readwrite').delete(id);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}
function parseName(name){const clean=String(name||'Skladba').replace(/\.[^.]+$/,'').replace(/_/g,' ').trim();const p=clean.split(/\s+-\s+/);return p.length>1?{artist:p.shift().trim(),title:p.join(' - ').trim()}:{artist:'Offline',title:clean}}
function human(n){n=Number(n)||0;return n>1048576?(n/1048576).toFixed(1)+' MB':Math.max(1,Math.round(n/1024))+' KB'}
function stopYoutube(){try{if(typeof player!=='undefined'&&player?.pauseVideo)player.pauseVideo()}catch{}}
function releaseUrl(){if(currentUrl){try{URL.revokeObjectURL(currentUrl)}catch{}currentUrl=''}}
function syncLabels(){if(!currentRec)return;const title=currentRec.title||currentRec.name||'Offline skladba',artist=currentRec.artist||'Offline';['now','pcurrent','bname','miniNowTitle'].forEach(id=>{const e=$(id);if(e)e.textContent=title});['sub','bmeta','miniNowSub'].forEach(id=>{const e=$(id);if(e)e.textContent=artist+' · Offline'});const pb=document.querySelector('.pbrand');if(pb)pb.textContent='Offline'}
function syncTick(){if(!offlineMode||!currentRec)return;const c=audio.currentTime||0,d=audio.duration||0,p=!audio.paused&&!audio.ended;const seek=$('seek'),mini=$('miniSeek');if(seek)seek.value=d?Math.round(c/d*1000):0;if(mini)mini.value=d?Math.round(c/d*1000):0;const bt=$('btime');if(bt)bt.textContent=fmt(c)+' / '+fmt(d);const a=$('miniNowTime'),b=$('miniTotalTime');if(a)a.textContent=fmt(c);if(b)b.textContent=fmt(d);['play','bplay','miniPlay'].forEach(id=>{const e=$(id);if(e)e.textContent=p?'⏸':'▶'});try{if('mediaSession'in navigator)navigator.mediaSession.playbackState=p?'playing':'paused'}catch{}}
async function playAt(i){if(!list.length)return;currentIndex=(i+list.length)%list.length;currentRec=list[currentIndex];stopYoutube();audio.pause();releaseUrl();currentUrl=URL.createObjectURL(currentRec.blob);audio.src=currentUrl;syncLabels();try{if('mediaSession'in navigator)navigator.mediaSession.metadata=new MediaMetadata({title:currentRec.title||currentRec.name,artist:currentRec.artist||'Offline',album:'Tesla Music · Offline'})}catch{};try{await audio.play()}catch{}syncTick()}
function next(){if(list.length)playAt(currentIndex<0?0:currentIndex+1)}function prev(){if(list.length)playAt(currentIndex<0?0:currentIndex-1)}function toggle(){if(!currentRec){if(list.length)playAt(0);return}audio.paused?audio.play().catch(()=>{}):audio.pause();syncTick()}
function render(){const grid=$('grid'),title=$('sectionTitle');if(!grid||!title)return;title.textContent='Offline knižnica';const total=list.reduce((n,x)=>n+(x.size||0),0);grid.innerHTML=`<div class="offline-tools"><button id="offlineAdd" class="btn offline-add">＋ Pridať skladby</button><div class="offline-summary">${list.length} skladieb · ${human(total)} · uložené iba v tomto zariadení</div></div>`+(list.length?list.map((x,i)=>`<div class="offline-card" data-offline-play="${i}"><div class="offline-note">♫</div><div class="offline-info"><div class="ctitle">${esc(x.title||x.name)}</div><div class="meta">${esc(x.artist||'Offline')} · ${human(x.size)}</div></div><button class="offline-delete" data-offline-delete="${esc(x.id)}" aria-label="Odstrániť">×</button></div>`).join(''):`<div class="empty offline-empty">Žiadne offline skladby.<br><small>Ťukni na „Pridať skladby“ a vyber MP3/M4A z aplikácie Súbory.</small></div>`);$('offlineAdd')?.addEventListener('click',()=>file.click());grid.querySelectorAll('[data-offline-play]').forEach(e=>e.addEventListener('click',ev=>{if(ev.target.closest('[data-offline-delete]'))return;playAt(Number(e.dataset.offlinePlay))}));grid.querySelectorAll('[data-offline-delete]').forEach(e=>e.addEventListener('click',async ev=>{ev.stopPropagation();const id=e.dataset.offlineDelete;if(currentRec?.id===id){audio.pause();currentRec=null;currentIndex=-1;releaseUrl()}await del(id);list=await all();render()}))}
async function enter(){offlineMode=true;document.body.classList.add('offline-mode');document.querySelectorAll('.chip').forEach(x=>x.classList.remove('active'));offlineBtn.classList.add('active');const h=$('history');if(h)h.classList.remove('show');list=await all();render();syncTick()}
function leave(){if(!offlineMode)return;offlineMode=false;document.body.classList.remove('offline-mode');offlineBtn.classList.remove('active');audio.pause();syncTick();const pb=document.querySelector('.pbrand');if(pb)pb.textContent='YouTube'}
const tabs=document.querySelector('.tabs');if(!tabs)return;const offlineBtn=document.createElement('button');offlineBtn.className='chip';offlineBtn.id='offlineTab';offlineBtn.textContent='Offline';offlineBtn.type='button';tabs.appendChild(offlineBtn);offlineBtn.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();enter()});
document.querySelectorAll('[data-tab]').forEach(b=>b.addEventListener('click',()=>leave(),true));
const file=document.createElement('input');file.type='file';file.accept='audio/*,.mp3,.m4a,.aac,.wav';file.multiple=true;file.style.display='none';document.body.appendChild(file);file.addEventListener('change',async()=>{const files=[...file.files||[]];if(!files.length)return;const status=$('status');if(status)status.textContent='Ukladám offline skladby…';for(const f of files){if(!f.type.startsWith('audio/')&&!/\.(mp3|m4a|aac|wav)$/i.test(f.name))continue;const n=parseName(f.name),id='off:'+Date.now()+':'+Math.random().toString(36).slice(2);await put({id,name:f.name,title:n.title,artist:n.artist,type:f.type||'audio/mpeg',size:f.size,addedAt:Date.now(),blob:f})}file.value='';list=await all();render();if(status)status.textContent='Offline skladby uložené v zariadení';try{await navigator.storage?.persist?.()}catch{}});
function capture(id,fn){const e=$(id);if(!e)return;e.addEventListener('click',ev=>{if(!offlineMode)return;ev.preventDefault();ev.stopImmediatePropagation();fn()},true)}
capture('play',toggle);capture('bplay',toggle);capture('miniPlay',toggle);capture('next',next);capture('bnext',next);capture('miniNext',next);capture('prev',prev);capture('bprev',prev);capture('miniPrev',prev);capture('restore',()=>{});capture('binfo',()=>{});
['seek','miniSeek'].forEach(id=>{const e=$(id);if(!e)return;e.addEventListener('change',ev=>{if(!offlineMode||!Number.isFinite(audio.duration))return;ev.stopImmediatePropagation();audio.currentTime=Number(e.value)/1000*audio.duration;syncTick()},true)});
audio.addEventListener('timeupdate',syncTick);audio.addEventListener('play',syncTick);audio.addEventListener('pause',syncTick);audio.addEventListener('loadedmetadata',syncTick);audio.addEventListener('ended',next);
try{if('mediaSession'in navigator){navigator.mediaSession.setActionHandler('play',()=>offlineMode?toggle():player?.playVideo?.());navigator.mediaSession.setActionHandler('pause',()=>offlineMode?toggle():player?.pauseVideo?.());navigator.mediaSession.setActionHandler('nexttrack',()=>offlineMode?next():window.next?.(true));navigator.mediaSession.setActionHandler('previoustrack',()=>offlineMode?prev():window.prev?.());navigator.mediaSession.setActionHandler('seekto',d=>{if(offlineMode&&Number.isFinite(d.seekTime))audio.currentTime=d.seekTime})}}catch{}
openDB().then(async()=>{list=await all();try{await navigator.storage?.persist?.()}catch{}}).catch(e=>{console.warn('Offline DB',e);offlineBtn.disabled=true;offlineBtn.title='Offline úložisko nie je dostupné'});
})();