(()=>{
'use strict';
if(window.__TESLA_OFFLINE_V23__)return;window.__TESLA_OFFLINE_V23__=true;
const st=document.createElement('style');st.textContent=`
.offline-tools{grid-column:1/-1;display:flex;align-items:center;gap:12px;flex-wrap:wrap;margin-bottom:4px}.offline-add{min-width:170px}.offline-bulk{min-width:220px}.offline-summary{color:var(--muted);font-size:14px}.offline-card{grid-column:1/-1;display:grid;grid-template-columns:54px minmax(0,1fr) 48px;align-items:center;gap:10px;background:var(--panel);border:1px solid var(--line);border-radius:14px;padding:9px 10px;cursor:pointer;min-height:70px}.offline-note{width:50px;height:50px;border-radius:12px;background:var(--panel2);display:flex;align-items:center;justify-content:center;font-size:26px}.offline-info{min-width:0}.offline-info .ctitle{white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.offline-delete{width:44px;height:44px;border:1px solid var(--line);border-radius:12px;background:var(--panel2);color:var(--text);font-size:26px}.offline-empty{grid-column:1/-1}.offline-empty small{display:block;margin-top:8px;line-height:1.4}.offline-mode .video{visibility:hidden}.offline-mode #like,.offline-mode #shuffle,.offline-mode #auto{visibility:hidden}.thumb-wrap{position:relative}.off-one{position:absolute;left:8px;bottom:8px;z-index:5;height:34px;border:1px solid rgba(255,255,255,.65);border-radius:10px;background:rgba(10,15,22,.86);color:#fff;padding:0 10px;font-size:12px;font-weight:800;backdrop-filter:blur(6px)}.off-one.ok{background:rgba(20,110,65,.9)}.off-one.busy{background:rgba(75,78,22,.9)}.off-one.fail{background:rgba(125,45,45,.9)}
@media(max-width:600px){.offline-tools{display:grid;grid-template-columns:1fr;gap:8px}.offline-add,.offline-bulk{width:100%;height:50px}.offline-summary{font-size:12px;padding:0 2px}.offline-card{grid-template-columns:48px minmax(0,1fr) 44px;min-height:66px;padding:8px}.offline-note{width:44px;height:44px;font-size:23px}.offline-info .ctitle{font-size:15px}.offline-info .meta{font-size:12px}.offline-delete{width:40px;height:40px}.offline-mode .content{padding-bottom:calc(108px + env(safe-area-inset-bottom))!important}.off-one{height:36px;font-size:12px;left:7px;bottom:7px}}
`;document.head.appendChild(st);
const DB='teslaMusicOfflineV1',STORE='tracks',QUEUE='https://dimvegkezslqjtsxdohp.supabase.co/functions/v1/twmusic-offline-queue';
const DEVICE_KEY='teslaMusic:offlineDevice:v1';
let deviceId=localStorage.getItem(DEVICE_KEY);if(!deviceId){deviceId=(crypto.randomUUID?.()||('d-'+Date.now()+'-'+Math.random().toString(36).slice(2)));localStorage.setItem(DEVICE_KEY,deviceId)}
let db=null,offlineMode=false,list=[],currentIndex=-1,currentRec=null,currentUrl='',decorating=false,syncing=false;
const states=new Map(),jobs=new Map();
const audio=new Audio();audio.preload='metadata';audio.setAttribute('playsinline','');document.body.appendChild(audio);audio.style.display='none';
const $=id=>document.getElementById(id),fmt=v=>{v=Math.max(0,Math.floor(Number(v)||0));return Math.floor(v/60)+':'+String(v%60).padStart(2,'0')};
const esc=s=>String(s||'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[m]));
function openDB(){return new Promise((res,rej)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>{const d=r.result;if(!d.objectStoreNames.contains(STORE))d.createObjectStore(STORE,{keyPath:'id'})};r.onsuccess=()=>{db=r.result;res(db)};r.onerror=()=>rej(r.error)})}
function tx(mode='readonly'){return db.transaction(STORE,mode).objectStore(STORE)}
function all(){return new Promise((res,rej)=>{const r=tx().getAll();r.onsuccess=()=>res((r.result||[]).sort((a,b)=>(b.addedAt||0)-(a.addedAt||0)));r.onerror=()=>rej(r.error)})}
function put(x){return new Promise((res,rej)=>{const r=tx('readwrite').put(x);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}
function del(id){return new Promise((res,rej)=>{const r=tx('readwrite').delete(id);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}
function parseName(name){const clean=String(name||'Skladba').replace(/\.[^.]+$/,'').replace(/_/g,' ').trim();const p=clean.split(/\s+-\s+/);return p.length>1?{artist:p.shift().trim(),title:p.join(' - ').trim()}:{artist:'Offline',title:clean}}
function human(n){n=Number(n)||0;return n>1048576?(n/1048576).toFixed(1)+' MB':Math.max(1,Math.round(n/1024))+' KB'}
function ytId(t){return String(t?.youtubeId||t?.id||'').replace(/^youtube:/,'').replace(/^yt:/,'')}
async function q(body){const r=await fetch(QUEUE,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...body,deviceId}),cache:'no-store'});const p=await r.json().catch(()=>({}));if(!r.ok||p.ok===false)throw new Error(p.error||('queue '+r.status));return p}
function stopYoutube(){try{if(typeof player!=='undefined'&&player?.pauseVideo)player.pauseVideo()}catch{}}
function releaseUrl(){if(currentUrl){try{URL.revokeObjectURL(currentUrl)}catch{}currentUrl=''}}
function syncLabels(){if(!currentRec)return;const title=currentRec.title||currentRec.name||'Offline skladba',artist=currentRec.artist||'Offline';['now','pcurrent','bname','miniNowTitle'].forEach(id=>{const e=$(id);if(e)e.textContent=title});['sub','bmeta','miniNowSub'].forEach(id=>{const e=$(id);if(e)e.textContent=artist+' · Offline'});const pb=document.querySelector('.pbrand');if(pb)pb.textContent='Offline'}
function syncTick(){if(!offlineMode||!currentRec)return;const c=audio.currentTime||0,d=audio.duration||0,p=!audio.paused&&!audio.ended;const seek=$('seek'),mini=$('miniSeek');if(seek)seek.value=d?Math.round(c/d*1000):0;if(mini)mini.value=d?Math.round(c/d*1000):0;const bt=$('btime');if(bt)bt.textContent=fmt(c)+' / '+fmt(d);const a=$('miniNowTime'),b=$('miniTotalTime');if(a)a.textContent=fmt(c);if(b)b.textContent=fmt(d);['play','bplay','miniPlay'].forEach(id=>{const e=$(id);if(e)e.textContent=p?'⏸':'▶'});try{if('mediaSession'in navigator)navigator.mediaSession.playbackState=p?'playing':'paused'}catch{}}
async function playAt(i){if(!list.length)return;currentIndex=(i+list.length)%list.length;currentRec=list[currentIndex];stopYoutube();audio.pause();releaseUrl();currentUrl=URL.createObjectURL(currentRec.blob);audio.src=currentUrl;syncLabels();try{if('mediaSession'in navigator)navigator.mediaSession.metadata=new MediaMetadata({title:currentRec.title||currentRec.name,artist:currentRec.artist||'Offline',album:'Tesla Music · Offline'})}catch{};try{await audio.play()}catch{}syncTick()}
function next(){if(list.length)playAt(currentIndex<0?0:currentIndex+1)}function prev(){if(list.length)playAt(currentIndex<0?0:currentIndex-1)}function toggle(){if(!currentRec){if(list.length)playAt(0);return}audio.paused?audio.play().catch(()=>{}):audio.pause();syncTick()}
function stateText(id){const s=states.get(id);return s==='ok'?'✓ Offline':s==='queued'?'⏳ Na pozadí':s==='ready'?'⏳ Ukladám':s==='fail'?'! Nenájdené':'↓ Offline'}
function mapStatus(s){if(['wanted_offline','resolving','retry'].includes(s))return'queued';if(s==='ready_to_cache')return'ready';if(['not_found','error'].includes(s))return'fail';if(s==='cached')return'cached';return''}
async function refreshLocal(){list=await all();for(const x of list){const id=String(x.youtubeId||'');if(id)states.set(id,'ok')}}
async function refreshJobs(){if(!navigator.onLine)return;try{const p=await q({mode:'jobs'});jobs.clear();for(const j of p.jobs||[]){jobs.set(j.youtube_id,j);if(states.get(j.youtube_id)==='ok')continue;const s=mapStatus(j.status);if(s&&s!=='cached')states.set(j.youtube_id,s);else if(s==='cached')states.delete(j.youtube_id)}paintAll()}catch{}}
async function submitBackground(t,btn){const id=ytId(t);if(!id)return false;if(states.get(id)==='ok')return true;states.set(id,'queued');paint(btn,id);try{const p=await q({mode:'submit',youtubeId:id,title:t.title||'',artist:t.uploader||t.artist||''});if(p.job){jobs.set(id,p.job);const s=mapStatus(p.job.status);states.set(id,s==='cached'?'queued':(s||'queued'))}paint(btn,id);setTimeout(syncReady,1800);return true}catch(e){states.set(id,'fail');paint(btn,id);return false}}
async function syncReady(){if(syncing||!navigator.onLine||!db)return;syncing=true;try{const p=await q({mode:'ready'});for(const j of p.jobs||[]){const id=String(j.youtube_id||'');if(!id||states.get(id)==='ok')continue;states.set(id,'ready');paintAll();try{const ar=await fetch(j.proxy_url,{cache:'no-store'});if(!ar.ok)throw new Error('download '+ar.status);const blob=await ar.blob();if(blob.size<200000)throw new Error('small audio');await put({id:'yt:'+id,youtubeId:id,name:j.file_name||((j.title||'Skladba')+'.mp3'),title:j.title||j.source_title||'Skladba',artist:j.artist||j.source_artist||'Offline',type:blob.type||j.content_type||'audio/mpeg',size:blob.size,addedAt:Date.now(),blob,source:j.source||'Offline resolver',license:j.license||'',sourcePage:j.source_page||''});await q({mode:'cached',id:j.id});states.set(id,'ok')}catch(e){states.set(id,'ready')}}await refreshLocal();paintAll();if(offlineMode)render()}catch{}finally{syncing=false}}
async function refreshStates(){states.clear();await refreshLocal();await refreshJobs();await syncReady()}
function paint(btn,id){if(!btn)return;const s=states.get(id)||'';btn.textContent=stateText(id);btn.classList.toggle('ok',s==='ok');btn.classList.toggle('busy',s==='queued'||s==='ready');btn.classList.toggle('fail',s==='fail')}
function trackForCard(c){try{return typeof items!=='undefined'?items[Number(c.dataset.i)]:null}catch{return null}}
function decorate(){if(offlineMode||decorating)return;decorating=true;try{document.querySelectorAll('#grid .card[data-i]').forEach(c=>{const t=trackForCard(c),id=ytId(t);if(!t||!id)return;let b=c.querySelector('.off-one');if(!b){b=document.createElement('button');b.className='off-one';b.type='button';c.querySelector('.thumb-wrap')?.appendChild(b);b.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();submitBackground(trackForCard(c),b)})}paint(b,id)})}finally{decorating=false}}
function paintAll(){decorate();document.querySelectorAll('.off-one').forEach(b=>{const c=b.closest('.card'),t=c?trackForCard(c):null,id=ytId(t);if(id)paint(b,id)})}
function pendingCount(){let n=0;for(const s of states.values())if(s==='queued'||s==='ready')n++;return n}
function render(){const grid=$('grid'),title=$('sectionTitle');if(!grid||!title)return;title.textContent='Offline knižnica';const total=list.reduce((n,x)=>n+(x.size||0),0),pending=pendingCount();grid.innerHTML=`<div class="offline-tools"><button id="offlineAdd" class="btn offline-add">＋ Pridať skladby</button><button id="offlineBulk" class="btn offline-bulk">↓ Pripraviť obľúbené offline</button><div class="offline-summary">${list.length} skladieb · ${human(total)}${pending?' · '+pending+' na pozadí':''} · uložené iba v tomto zariadení</div></div>`+(list.length?list.map((x,i)=>`<div class="offline-card" data-offline-play="${i}"><div class="offline-note">♫</div><div class="offline-info"><div class="ctitle">${esc(x.title||x.name)}</div><div class="meta">${esc(x.artist||'Offline')} · ${human(x.size)}</div></div><button class="offline-delete" data-offline-delete="${esc(x.id)}" aria-label="Odstrániť">×</button></div>`).join(''):`<div class="empty offline-empty">Žiadne uložené offline skladby.<br><small>${pending?pending+' skladieb sa spracúva na serveri. Piped ich prevezme pri najbližšom otvorení online.':'Pridaj vlastné MP3/M4A alebo použi „Pripraviť obľúbené offline“.'}</small></div>`);$('offlineAdd')?.addEventListener('click',()=>file.click());$('offlineBulk')?.addEventListener('click',bulkLikes);grid.querySelectorAll('[data-offline-play]').forEach(e=>e.addEventListener('click',ev=>{if(ev.target.closest('[data-offline-delete]'))return;playAt(Number(e.dataset.offlinePlay))}));grid.querySelectorAll('[data-offline-delete]').forEach(e=>e.addEventListener('click',async ev=>{ev.stopPropagation();const id=e.dataset.offlineDelete;if(currentRec?.id===id){audio.pause();currentRec=null;currentIndex=-1;releaseUrl()}await del(id);await refreshStates();render()}))}
async function bulkLikes(){let likes=[];try{likes=Object.values(profile?.tracks||{}).filter(x=>x.liked).map(x=>({id:x.youtubeId,title:x.title,uploader:x.artist}))}catch{}const b=$('offlineBulk');let sent=0;for(let i=0;i<likes.length;i++){const t=likes[i],id=ytId(t);if(states.get(id)==='ok'||states.get(id)==='queued')continue;if(b)b.textContent=`⏳ ${i+1}/${likes.length}`;if(await submitBackground(t,null))sent++}if(b)b.textContent=`✓ Na pozadí · ${sent}`;await refreshJobs();if(offlineMode)render()}
async function enter(){offlineMode=true;document.body.classList.add('offline-mode');document.querySelectorAll('.chip').forEach(x=>x.classList.remove('active'));offlineBtn.classList.add('active');const h=$('history');if(h)h.classList.remove('show');await refreshStates();render();syncTick()}
function leave(){if(!offlineMode)return;offlineMode=false;document.body.classList.remove('offline-mode');offlineBtn.classList.remove('active');audio.pause();syncTick();const pb=document.querySelector('.pbrand');if(pb)pb.textContent='YouTube';setTimeout(paintAll,0)}
const tabs=document.querySelector('.tabs');if(!tabs)return;const offlineBtn=document.createElement('button');offlineBtn.className='chip';offlineBtn.id='offlineTab';offlineBtn.textContent='Offline';offlineBtn.type='button';tabs.appendChild(offlineBtn);offlineBtn.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();enter()});
document.querySelectorAll('[data-tab]').forEach(b=>b.addEventListener('click',()=>leave(),true));
const file=document.createElement('input');file.type='file';file.accept='audio/*,.mp3,.m4a,.aac,.wav';file.multiple=true;file.style.display='none';document.body.appendChild(file);file.addEventListener('change',async()=>{const files=[...file.files||[]];if(!files.length)return;const status=$('status');if(status)status.textContent='Ukladám offline skladby…';for(const f of files){if(!f.type.startsWith('audio/')&&!/\.(mp3|m4a|aac|wav)$/i.test(f.name))continue;const n=parseName(f.name),id='off:'+Date.now()+':'+Math.random().toString(36).slice(2);await put({id,name:f.name,title:n.title,artist:n.artist,type:f.type||'audio/mpeg',size:f.size,addedAt:Date.now(),blob:f})}file.value='';await refreshLocal();render();if(status)status.textContent='Offline skladby uložené v zariadení';try{await navigator.storage?.persist?.()}catch{}});
function capture(id,fn){const e=$(id);if(!e)return;e.addEventListener('click',ev=>{if(!offlineMode)return;ev.preventDefault();ev.stopImmediatePropagation();fn()},true)}
capture('play',toggle);capture('bplay',toggle);capture('miniPlay',toggle);capture('next',next);capture('bnext',next);capture('miniNext',next);capture('prev',prev);capture('bprev',prev);capture('miniPrev',prev);capture('restore',()=>{});capture('binfo',()=>{});
['seek','miniSeek'].forEach(id=>{const e=$(id);if(!e)return;e.addEventListener('change',ev=>{if(!offlineMode||!Number.isFinite(audio.duration))return;ev.stopImmediatePropagation();audio.currentTime=Number(e.value)/1000*audio.duration;syncTick()},true)});
audio.addEventListener('timeupdate',syncTick);audio.addEventListener('play',syncTick);audio.addEventListener('pause',syncTick);audio.addEventListener('loadedmetadata',syncTick);audio.addEventListener('ended',next);
try{if('mediaSession'in navigator){navigator.mediaSession.setActionHandler('play',()=>offlineMode?toggle():player?.playVideo?.());navigator.mediaSession.setActionHandler('pause',()=>offlineMode?toggle():player?.pauseVideo?.());navigator.mediaSession.setActionHandler('nexttrack',()=>offlineMode?next():document.getElementById('next')?.click());navigator.mediaSession.setActionHandler('previoustrack',()=>offlineMode?prev():document.getElementById('prev')?.click());navigator.mediaSession.setActionHandler('seekto',d=>{if(offlineMode&&Number.isFinite(d.seekTime))audio.currentTime=d.seekTime})}}catch{}
async function foregroundSync(){if(!db||!navigator.onLine)return;await refreshJobs();await syncReady();paintAll();if(offlineMode)render()}
window.addEventListener('online',foregroundSync);window.addEventListener('focus',foregroundSync);document.addEventListener('visibilitychange',()=>{if(!document.hidden)foregroundSync()});
openDB().then(async()=>{await refreshStates();try{await navigator.storage?.persist?.()}catch{};setTimeout(paintAll,300);setInterval(()=>{if(!offlineMode)decorate()},1600);setInterval(foregroundSync,20000)}).catch(e=>{console.warn('Offline DB',e);offlineBtn.disabled=true;offlineBtn.title='Offline úložisko nie je dostupné'});
})();