(()=>{
'use strict';
const qs=new URLSearchParams(location.search);
if(qs.get('map')==='1'||qs.get('embed')==='1')return;
if(window.__TESLA_OFFLINE_V25__)return;window.__TESLA_OFFLINE_V25__=true;

const JAMENDO_CLIENT_ID='709fa152';
const MIN_AUDIO_BYTES=200000;
const REQUEST_TIMEOUT=9000;

const st=document.createElement('style');st.textContent=`
.offline-tools{grid-column:1/-1;display:flex;align-items:center;gap:12px;flex-wrap:wrap;margin-bottom:4px}.offline-add{min-width:170px}.offline-bulk{min-width:220px}.offline-summary{color:var(--muted);font-size:14px}.offline-card{grid-column:1/-1;display:grid;grid-template-columns:54px minmax(0,1fr) 48px;align-items:center;gap:10px;background:var(--panel);border:1px solid var(--line);border-radius:14px;padding:9px 10px;cursor:pointer;min-height:70px}.offline-note{width:50px;height:50px;border-radius:12px;background:var(--panel2);display:flex;align-items:center;justify-content:center;font-size:26px}.offline-info{min-width:0}.offline-info .ctitle{white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.offline-delete{width:44px;height:44px;border:1px solid var(--line);border-radius:12px;background:var(--panel2);color:var(--text);font-size:26px}.offline-empty{grid-column:1/-1}.offline-empty small{display:block;margin-top:8px;line-height:1.4}.offline-mode .video{visibility:hidden}.offline-mode #like,.offline-mode #shuffle,.offline-mode #auto{visibility:hidden}.thumb-wrap{position:relative}.off-one{position:absolute;left:8px;bottom:8px;z-index:5;height:34px;border:1px solid rgba(255,255,255,.65);border-radius:10px;background:rgba(10,15,22,.86);color:#fff;padding:0 10px;font-size:12px;font-weight:800;backdrop-filter:blur(6px)}.off-one.ok{background:rgba(20,110,65,.9)}.off-one.busy{background:rgba(75,78,22,.9)}.off-one.fail{background:rgba(125,45,45,.9)}
@media(max-width:600px){.offline-tools{display:grid;grid-template-columns:1fr;gap:8px}.offline-add,.offline-bulk{width:100%;height:50px}.offline-summary{font-size:12px;padding:0 2px}.offline-card{grid-template-columns:48px minmax(0,1fr) 44px;min-height:66px;padding:8px}.offline-note{width:44px;height:44px;font-size:23px}.offline-info .ctitle{font-size:15px}.offline-info .meta{font-size:12px}.offline-delete{width:40px;height:40px}.offline-mode .content{padding-bottom:calc(108px + env(safe-area-inset-bottom))!important}.off-one{height:36px;font-size:12px;left:7px;bottom:7px}}
`;document.head.appendChild(st);

const DB='teslaMusicOfflineV1',STORE='tracks';
let db=null,offlineMode=false,list=[],currentIndex=-1,currentRec=null,currentUrl='',decorating=false;
const states=new Map();
const audio=new Audio();audio.preload='metadata';audio.setAttribute('playsinline','');document.body.appendChild(audio);audio.style.display='none';
const $=id=>document.getElementById(id),fmt=v=>{v=Math.max(0,Math.floor(Number(v)||0));return Math.floor(v/60)+':'+String(v%60).padStart(2,'0')};
const esc=s=>String(s||'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[m]));

function openDB(){return new Promise((res,rej)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>{const d=r.result;if(!d.objectStoreNames.contains(STORE))d.createObjectStore(STORE,{keyPath:'id'})};r.onsuccess=()=>{db=r.result;res(db)};r.onerror=()=>rej(r.error)})}
function tx(mode='readonly'){return db.transaction(STORE,mode).objectStore(STORE)}
function all(){return new Promise((res,rej)=>{const r=tx().getAll();r.onsuccess=()=>res((r.result||[]).sort((a,b)=>(b.addedAt||0)-(a.addedAt||0)));r.onerror=()=>rej(r.error)})}
function put(x){return new Promise((res,rej)=>{const r=tx('readwrite').put(x);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}
function del(id){return new Promise((res,rej)=>{const r=tx('readwrite').delete(id);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}
function parseName(name){const clean=String(name||'Skladba').replace(/\.[^.]+$/,'').replace(/_/g,' ').trim();const p=clean.split(/\s+-\s+/);return p.length>1?{artist:p.shift().trim(),title:p.join(' - ').trim()}:{artist:'Offline',title:clean}}
function human(n){n=Number(n)||0;return n>1048576?(n/1048576).toFixed(1)+' MB':Math.max(1,Math.round(n/1024))+' KB'}
function ytId(t){return String(t?.youtubeId||t?.id||'').replace(/^youtube:/,'').replace(/^yt:/,'')}

function clean(s){return String(s||'')
 .replace(/\([^)]*(official|lyrics?|visuali[sz]er|audio|video)[^)]*\)/ig,'')
 .replace(/\[[^\]]*(official|lyrics?|visuali[sz]er|audio|video)[^\]]*\]/ig,'')
 .replace(/\s+-\s+topic$/ig,'')
 .replace(/\b(official\s+(music\s+)?video|official\s+audio|lyrics?|visuali[sz]er)\b/ig,'')
 .replace(/\s+/g,' ').trim()}
function fold(s){return clean(s).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim()}
function toks(s){return new Set(fold(s).split(/\s+/).filter(Boolean))}
function sim(a,b){const A=toks(a),B=toks(b);if(!A.size||!B.size)return 0;let n=0;for(const x of A)if(B.has(x))n++;return 2*n/(A.size+B.size)}
function dashParts(s){return String(s||'').split(/\s+[-–—]\s+/).map(x=>x.trim()).filter(Boolean)}
function candidateScore(qt,qa,t,a){const ps=dashParts(t);const ts=Math.max(sim(qt,t),...ps.map(x=>sim(qt,x)),0),as=qa?Math.max(sim(qa,a),...ps.map(x=>sim(qa,x)),0):1;if(ts<.66)return 0;if(qa&&as<.25)return 0;return ts*.78+as*.22}
function genericUploader(a){return /^(audio library|youtube|various artists|music|topic|unknown)$/i.test(fold(a))}
function requestIdentity(title,artist){let t=String(title||'').replace(/\([^)]*(no copyright|copyright free|royalty free)[^)]*\)/ig,'').replace(/\[[^\]]*(no copyright|copyright free|royalty free)[^\]]*\]/ig,'').replace(/\s+/g,' ').trim(),a=clean(artist);if(genericUploader(a)){const ps=dashParts(t);if(ps.length>=2){const left=clean(ps[0]),right=clean(ps.slice(1).join(' - '));if(left&&right&&right.split(/\s+/).length<=6){t=left;a=right}else{a=''}}else a=''}return{title:clean(t),artist:a}}
function allowedLicense(v){const x=String(v||'').toLowerCase().trim();if(!x)return false;if(/all rights reserved|access restricted|non[- ]?free/.test(x))return false;if(/creativecommons\.org|creative commons|public domain/.test(x))return true;return ['cc0','pdm','by','by-sa','by-nc','by-nc-sa','by-nd','by-nc-nd'].some(k=>x===k||x.includes(' '+k+' '))}
function isAudioName(v){return /\.(mp3|m4a|aac|ogg|oga|opus|flac|wav|webm)(?:$|\?)/i.test(String(v||''))}
function badName(v){return /sample|preview|excerpt|trailer|podcast|interview|audiobook/i.test(String(v||''))}
const versionWords=['live','remix','acoustic','instrumental','karaoke','cover','tribute','demo','radio edit','extended'];
function versionOk(requested,candidate){const r=fold(requested),c=fold(candidate);for(const v of versionWords){if(r.includes(v)!==c.includes(v))return false}return true}
function queryVariants(title,artist){const out=[];const push=s=>{s=String(s||'').replace(/\s+/g,' ').trim();if(s&&!out.includes(s))out.push(s)};const noFeat=title.replace(/\s+(feat\.?|ft\.?)\s+.+$/i,'').trim();push([title,artist].filter(Boolean).join(' '));push(title);push([noFeat,artist].filter(Boolean).join(' '));push(noFeat);return out.slice(0,4)}
async function fetchJson(url,timeout=REQUEST_TIMEOUT){const c=new AbortController(),tm=setTimeout(()=>c.abort(),timeout);try{const r=await fetch(url,{cache:'no-store',signal:c.signal,mode:'cors'});if(!r.ok)throw new Error('HTTP '+r.status);return await r.json()}finally{clearTimeout(tm)}}

async function resolveMusicBrainz(title,artist){try{const q=[`recording:${JSON.stringify(title)}`,artist?`artist:${JSON.stringify(artist)}`:''].filter(Boolean).join(' AND ');const j=await fetchJson(`https://musicbrainz.org/ws/2/recording/?query=${encodeURIComponent(q)}&fmt=json&limit=5`);for(const x of Array.isArray(j.recordings)?j.recordings:[]){if(Number(x.score||0)<75)continue;const a=(x['artist-credit']||[]).map(z=>z?.name||z?.artist?.name||'').filter(Boolean).join(' & ');if(candidateScore(title,artist,String(x.title||''),a)<.55)continue;return{title:String(x.title||title),artist:a||artist,id:String(x.id||'')}}}catch{}return{title,artist,id:''}}

async function findOpenverse(title,artist){const out=[];try{for(const q of queryVariants(title,artist).slice(0,3)){let j;try{j=await fetchJson(`https://api.openverse.org/v1/audio/?q=${encodeURIComponent(q)}&page_size=30`)}catch{continue}for(const x of Array.isArray(j.results)?j.results:[]){const lic=String(x.license_url||x.license||'');const ct=String(x.title||'');const url=String(x.url||'');if(!allowedLicense(lic)||!versionOk(title,ct)||badName(ct)||!/^https:\/\//i.test(url))continue;const score=candidateScore(title,artist,ct,String(x.creator||''));if(score<.62)continue;out.push({kind:'ov',title:ct,artist:String(x.creator||artist),audioUrl:url,license:lic,source:'Openverse · '+String(x.source||x.provider||'Audio'),sourcePage:String(x.foreign_landing_url||x.frontend_url||''),score})}if(out.some(x=>x.score>=.93))break}}catch{}return out.sort((a,b)=>b.score-a.score).slice(0,5)}

async function archiveMeta(id){return await fetchJson(`https://archive.org/metadata/${encodeURIComponent(id)}`,11000)}
function archiveRightsOk(m){const x=[m?.licenseurl,m?.rights,m?.usage,m?.collection].flat().filter(Boolean).join(' ').toLowerCase();return /creativecommons|creative commons|public domain|cc0|opensource_audio|netlabels|audio_music/.test(x)&&!/all rights reserved|access restricted/.test(x)}
async function findArchive(title,artist){const out=[];try{const escQ=s=>String(s||'').replaceAll('"','');const queries=[[`title:(\"${escQ(title)}\")`,artist?`creator:(\"${escQ(artist)}\")`:'','mediatype:(audio)'].filter(Boolean).join(' AND '),[`title:(\"${escQ(title)}\")`,'mediatype:(audio)'].join(' AND ')];const terms=fold(title).split(' ').filter(Boolean).slice(0,7).join(' AND ');if(terms)queries.push(`(${terms}) AND mediatype:(audio)`);const seen=new Set();for(const q of queries){let j;try{j=await fetchJson(`https://archive.org/advancedsearch.php?q=${encodeURIComponent(q)}&fl[]=identifier&fl[]=title&fl[]=creator&fl[]=licenseurl&fl[]=rights&fl[]=collection&rows=15&page=1&output=json`,11000)}catch{continue}const docs=j?.response?.docs||[];const ranked=docs.map(d=>({...d,_score:candidateScore(title,artist,String(d.title||''),String(d.creator||''))})).filter(d=>d._score>=.62&&!badName(d.title)&&versionOk(title,String(d.title||''))).sort((a,b)=>b._score-a._score).slice(0,5);for(const d of ranked){const id=String(d.identifier||'');if(!id||seen.has(id))continue;seen.add(id);let md;try{md=await archiveMeta(id)}catch{continue}const m=md?.metadata||{};if(!archiveRightsOk({...m,...d}))continue;const files=(md?.files||[]).filter(f=>isAudioName(String(f.name||''))&&!badName(String(f.name||''))&&Number(f.size||0)>MIN_AUDIO_BYTES);if(!files.length)continue;const rank=n=>/\.mp3$/i.test(n)?5:/\.m4a$/i.test(n)?4:/\.aac$/i.test(n)?3:/\.(ogg|oga|opus)$/i.test(n)?2:/\.wav$/i.test(n)?1:0;files.sort((a,b)=>rank(String(b.name||''))-rank(String(a.name||''))||Number(a.size||0)-Number(b.size||0));const f=files[0],file=String(f.name||'');out.push({kind:'ia',title:String(m.title||d.title||title),artist:String(m.creator||d.creator||artist),audioUrl:`https://archive.org/download/${encodeURIComponent(id)}/${file.split('/').map(encodeURIComponent).join('/')}`,license:String(m.licenseurl||d.licenseurl||m.rights||d.rights||'verified archive collection'),source:'Internet Archive',sourcePage:`https://archive.org/details/${encodeURIComponent(id)}`,file,score:d._score})}if(out.some(x=>x.score>=.93))break}}catch{}return out.sort((a,b)=>b.score-a.score).slice(0,5)}

function metaVal(x,k){return String(x?.[k]?.value||'').replace(/<[^>]+>/g,' ').replace(/&nbsp;/g,' ').replace(/\s+/g,' ').trim()}
async function findCommons(title,artist){const out=[];try{for(const q of queryVariants(title,artist).slice(0,3)){let j;try{j=await fetchJson(`https://commons.wikimedia.org/w/api.php?action=query&generator=search&gsrsearch=${encodeURIComponent(q)}&gsrnamespace=6&gsrlimit=15&prop=imageinfo&iiprop=url|mime|size|extmetadata&format=json&formatversion=2&origin=*`,10000)}catch{continue}for(const p of j?.query?.pages||[]){const ii=p?.imageinfo?.[0];if(!ii)continue;const fileTitle=String(p.title||'').replace(/^File:/i,'').replace(/\.[^.]+$/,''),mime=String(ii.mime||'').toLowerCase(),url=String(ii.url||'');if((!mime.startsWith('audio/')&&!isAudioName(url))||Number(ii.size||0)<MIN_AUDIO_BYTES||badName(fileTitle)||!versionOk(title,fileTitle))continue;const ext=ii.extmetadata||{},lic=[metaVal(ext,'LicenseShortName'),metaVal(ext,'LicenseUrl'),metaVal(ext,'UsageTerms')].filter(Boolean).join(' ');if(!allowedLicense(lic))continue;const creator=[metaVal(ext,'Artist'),metaVal(ext,'Credit')].filter(Boolean).join(' '),score=candidateScore(title,artist,fileTitle,creator);if(score<.62)continue;out.push({kind:'wm',title:fileTitle,artist:creator||artist,audioUrl:url,license:lic,source:'Wikimedia Commons',sourcePage:String(ii.descriptionurl||''),score})}if(out.some(x=>x.score>=.93))break}}catch{}return out.sort((a,b)=>b.score-a.score).slice(0,5)}

async function findJamendo(title,artist){const out=[];try{for(const q of queryVariants(title,artist).slice(0,3)){let j;try{j=await fetchJson(`https://api.jamendo.com/v3.0/tracks/?client_id=${encodeURIComponent(JAMENDO_CLIENT_ID)}&format=json&limit=25&search=${encodeURIComponent(q)}&include=licenses&audioformat=mp32&audiodlformat=mp32`,10000)}catch{continue}for(const x of j?.results||[]){if(x.audiodownload_allowed!==true||!String(x.audiodownload||''))continue;const lic=String(x.license_ccurl||x.license?.ccurl||'');const ct=String(x.name||'');if(!allowedLicense(lic)||badName(ct)||!versionOk(title,ct))continue;const score=candidateScore(title,artist,ct,String(x.artist_name||''));if(score<.62)continue;out.push({kind:'jm',title:ct,artist:String(x.artist_name||artist),audioUrl:String(x.audiodownload),license:lic,source:'Jamendo',sourcePage:String(x.shareurl||x.shorturl||''),score})}if(out.some(x=>x.score>=.93))break}}catch{}return out.sort((a,b)=>b.score-a.score).slice(0,5)}

async function resolveCandidates(title,artist){const originalTitle=clean(title),originalArtist=clean(artist),canon=await resolveMusicBrainz(originalTitle,originalArtist),qt=canon.title||originalTitle,qa=canon.artist||originalArtist;const batches=await Promise.allSettled([findJamendo(qt,qa),findOpenverse(qt,qa),findArchive(qt,qa),findCommons(qt,qa)]);let all=[];for(const b of batches)if(b.status==='fulfilled')all.push(...b.value);const bonus={jm:.03,ov:.02,wm:.01,ia:0};all.sort((a,b)=>(b.score+(bonus[b.kind]||0))-(a.score+(bonus[a.kind]||0)));const seen=new Set();return all.filter(x=>{const k=fold(x.title)+'|'+fold(x.artist)+'|'+x.audioUrl;if(seen.has(k))return false;seen.add(k);return true}).slice(0,12)}

async function fetchAudio(c){const ctrl=new AbortController(),tm=setTimeout(()=>ctrl.abort(),20000);try{const r=await fetch(c.audioUrl,{cache:'no-store',mode:'cors',redirect:'follow',signal:ctrl.signal});if(!r.ok)throw new Error('audio '+r.status);const ct=String(r.headers.get('content-type')||'').toLowerCase();if(/text\/html|application\/json|text\/plain/.test(ct))throw new Error('not audio '+ct);const blob=await r.blob();if(blob.size<MIN_AUDIO_BYTES)throw new Error('small audio');return{blob,type:blob.type||ct||'audio/mpeg'}}finally{clearTimeout(tm)}}

function stopYoutube(){try{if(typeof player!=='undefined'&&player?.pauseVideo)player.pauseVideo()}catch{}}
function releaseUrl(){if(currentUrl){try{URL.revokeObjectURL(currentUrl)}catch{}currentUrl=''}}
function syncLabels(){if(!currentRec)return;const title=currentRec.title||currentRec.name||'Offline skladba',artist=currentRec.artist||'Offline';['now','pcurrent','bname','miniNowTitle'].forEach(id=>{const e=$(id);if(e)e.textContent=title});['sub','bmeta','miniNowSub'].forEach(id=>{const e=$(id);if(e)e.textContent=artist+' · Offline'});const pb=document.querySelector('.pbrand');if(pb)pb.textContent='Offline'}
function syncTick(){if(!offlineMode||!currentRec)return;const c=audio.currentTime||0,d=audio.duration||0,p=!audio.paused&&!audio.ended;const seek=$('seek'),mini=$('miniSeek');if(seek)seek.value=d?Math.round(c/d*1000):0;if(mini)mini.value=d?Math.round(c/d*1000):0;const bt=$('btime');if(bt)bt.textContent=fmt(c)+' / '+fmt(d);const a=$('miniNowTime'),b=$('miniTotalTime');if(a)a.textContent=fmt(c);if(b)b.textContent=fmt(d);['play','bplay','miniPlay'].forEach(id=>{const e=$(id);if(e)e.textContent=p?'⏸':'▶'});try{if('mediaSession'in navigator)navigator.mediaSession.playbackState=p?'playing':'paused'}catch{}}
async function playAt(i){if(!list.length)return;currentIndex=(i+list.length)%list.length;currentRec=list[currentIndex];stopYoutube();audio.pause();releaseUrl();currentUrl=URL.createObjectURL(currentRec.blob);audio.src=currentUrl;syncLabels();try{if('mediaSession'in navigator)navigator.mediaSession.metadata=new MediaMetadata({title:currentRec.title||currentRec.name,artist:currentRec.artist||'Offline',album:'Tesla Music · Offline'})}catch{};try{await audio.play()}catch{}syncTick()}
function next(){if(list.length)playAt(currentIndex<0?0:currentIndex+1)}function prev(){if(list.length)playAt(currentIndex<0?0:currentIndex-1)}function toggle(){if(!currentRec){if(list.length)playAt(0);return}audio.paused?audio.play().catch(()=>{}):audio.pause();syncTick()}
function stateText(id){const s=states.get(id);return s==='ok'?'✓ Offline':s==='queued'?'⏳ Hľadám':s==='ready'?'⏳ Ukladám':s==='fail'?'! Nenájdené':'↓ Offline'}
async function refreshLocal(){list=await all();for(const x of list){const id=String(x.youtubeId||'');if(id)states.set(id,'ok')}}
async function refreshStates(){states.clear();await refreshLocal()}
function paint(btn,id){if(!btn)return;const s=states.get(id)||'';btn.textContent=stateText(id);btn.classList.toggle('ok',s==='ok');btn.classList.toggle('busy',s==='queued'||s==='ready');btn.classList.toggle('fail',s==='fail')}
function trackForCard(c){try{return typeof items!=='undefined'?items[Number(c.dataset.i)]:null}catch{return null}}
function decorate(){if(offlineMode||decorating)return;decorating=true;try{document.querySelectorAll('#grid .card[data-i]').forEach(c=>{const t=trackForCard(c),id=ytId(t);if(!t||!id)return;let b=c.querySelector('.off-one');if(!b){b=document.createElement('button');b.className='off-one';b.type='button';c.querySelector('.thumb-wrap')?.appendChild(b);b.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();saveOffline(trackForCard(c),b)})}paint(b,id)})}finally{decorating=false}}
function paintAll(){decorate();document.querySelectorAll('.off-one').forEach(b=>{const c=b.closest('.card'),t=c?trackForCard(c):null,id=ytId(t);if(id)paint(b,id)})}
function pendingCount(){let n=0;for(const s of states.values())if(s==='queued'||s==='ready')n++;return n}

async function saveOffline(t,btn){const id=ytId(t);if(!id||!db||!navigator.onLine)return false;if(states.get(id)==='ok')return true;states.set(id,'queued');paint(btn,id);paintAll();const status=$('status');if(status)status.textContent='Hľadám povolenú offline verziu…';try{const rq=requestIdentity(t.title||'',t.uploader||t.artist||'');const candidates=await resolveCandidates(rq.title,rq.artist);if(!candidates.length)throw new Error('not_found');let last=null;for(const c of candidates){try{states.set(id,'ready');paint(btn,id);paintAll();if(status)status.textContent='Ukladám do iPhonu · '+c.source;const a=await fetchAudio(c);await put({id:'yt:'+id,youtubeId:id,name:(c.artist||'Offline')+' - '+(c.title||t.title||'Skladba'),title:c.title||t.title||'Skladba',artist:c.artist||t.uploader||t.artist||'Offline',type:a.type,size:a.blob.size,addedAt:Date.now(),blob:a.blob,source:c.source,license:c.license||'',sourcePage:c.sourcePage||'',originalTitle:t.title||'',originalArtist:t.uploader||t.artist||''});states.set(id,'ok');await refreshLocal();paintAll();if(offlineMode)render();if(status)status.textContent='✓ Offline uložené v tomto zariadení · '+c.source;try{await navigator.storage?.persist?.()}catch{}return true}catch(e){last=e;console.warn('Offline candidate failed',c.source,c.title,e)}}throw last||new Error('download_failed')}catch(e){states.set(id,'fail');paint(btn,id);paintAll();if(status)status.textContent='Offline verzia s povoleným stiahnutím sa nenašla';return false}}

function render(){const grid=$('grid'),title=$('sectionTitle');if(!grid||!title)return;title.textContent='Offline knižnica';const total=list.reduce((n,x)=>n+(x.size||0),0),pending=pendingCount();grid.innerHTML=`<div class="offline-tools"><button id="offlineAdd" class="btn offline-add">＋ Pridať skladby</button><button id="offlineBulk" class="btn offline-bulk">↓ Pripraviť obľúbené offline</button><div class="offline-summary">${list.length} skladieb · ${human(total)}${pending?' · '+pending+' spracúvam':''} · uložené iba v tomto zariadení</div></div>`+(list.length?list.map((x,i)=>`<div class="offline-card" data-offline-play="${i}"><div class="offline-note">♫</div><div class="offline-info"><div class="ctitle">${esc(x.title||x.name)}</div><div class="meta">${esc(x.artist||'Offline')} · ${human(x.size)} · ${esc(x.source||'Lokálny súbor')}</div></div><button class="offline-delete" data-offline-delete="${esc(x.id)}" aria-label="Odstrániť">×</button></div>`).join(''):`<div class="empty offline-empty">Žiadne uložené offline skladby.<br><small>Pri skladbe stlač „↓ Offline“ alebo pridaj vlastné MP3/M4A.</small></div>`);$('offlineAdd')?.addEventListener('click',()=>file.click());$('offlineBulk')?.addEventListener('click',bulkLikes);grid.querySelectorAll('[data-offline-play]').forEach(e=>e.addEventListener('click',ev=>{if(ev.target.closest('[data-offline-delete]'))return;playAt(Number(e.dataset.offlinePlay))}));grid.querySelectorAll('[data-offline-delete]').forEach(e=>e.addEventListener('click',async ev=>{ev.stopPropagation();const id=e.dataset.offlineDelete;if(currentRec?.id===id){audio.pause();currentRec=null;currentIndex=-1;releaseUrl()}await del(id);await refreshStates();render()}))}
async function bulkLikes(){let likes=[];try{likes=Object.values(profile?.tracks||{}).filter(x=>x.liked).map(x=>({id:x.youtubeId,title:x.title,uploader:x.artist}))}catch{}const b=$('offlineBulk');let saved=0;for(let i=0;i<likes.length;i++){const t=likes[i],id=ytId(t);if(states.get(id)==='ok')continue;if(b)b.textContent=`⏳ ${i+1}/${likes.length}`;if(await saveOffline(t,null))saved++}if(b)b.textContent=`✓ Uložené · ${saved}`;if(offlineMode)render()}
async function enter(){offlineMode=true;document.body.classList.add('offline-mode');document.querySelectorAll('.chip').forEach(x=>x.classList.remove('active'));offlineBtn.classList.add('active');const h=$('history');if(h)h.classList.remove('show');await refreshStates();render();syncTick()}
function leave(){if(!offlineMode)return;offlineMode=false;document.body.classList.remove('offline-mode');offlineBtn.classList.remove('active');audio.pause();syncTick();const pb=document.querySelector('.pbrand');if(pb)pb.textContent='YouTube';setTimeout(paintAll,0)}
const tabs=document.querySelector('.tabs');if(!tabs)return;const offlineBtn=document.createElement('button');offlineBtn.className='chip';offlineBtn.id='offlineTab';offlineBtn.textContent='Offline';offlineBtn.type='button';tabs.appendChild(offlineBtn);offlineBtn.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();enter()});
document.querySelectorAll('[data-tab]').forEach(b=>b.addEventListener('click',()=>leave(),true));
const file=document.createElement('input');file.type='file';file.accept='audio/*,.mp3,.m4a,.aac,.ogg,.opus,.flac,.wav';file.multiple=true;file.style.display='none';document.body.appendChild(file);file.addEventListener('change',async()=>{const files=[...file.files||[]];if(!files.length)return;const status=$('status');if(status)status.textContent='Ukladám offline skladby…';for(const f of files){if(!f.type.startsWith('audio/')&&!/\.(mp3|m4a|aac|ogg|opus|flac|wav)$/i.test(f.name))continue;const n=parseName(f.name),id='off:'+Date.now()+':'+Math.random().toString(36).slice(2);await put({id,name:f.name,title:n.title,artist:n.artist,type:f.type||'audio/mpeg',size:f.size,addedAt:Date.now(),blob:f,source:'Vlastný súbor'})}file.value='';await refreshLocal();render();if(status)status.textContent='Offline skladby uložené v zariadení';try{await navigator.storage?.persist?.()}catch{}});
function capture(id,fn){const e=$(id);if(!e)return;e.addEventListener('click',ev=>{if(!offlineMode)return;ev.preventDefault();ev.stopImmediatePropagation();fn()},true)}
capture('play',toggle);capture('bplay',toggle);capture('miniPlay',toggle);capture('next',next);capture('bnext',next);capture('miniNext',next);capture('prev',prev);capture('bprev',prev);capture('miniPrev',prev);capture('restore',()=>{});capture('binfo',()=>{});
['seek','miniSeek'].forEach(id=>{const e=$(id);if(!e)return;e.addEventListener('change',ev=>{if(!offlineMode||!Number.isFinite(audio.duration))return;ev.stopImmediatePropagation();audio.currentTime=Number(e.value)/1000*audio.duration;syncTick()},true)});
audio.addEventListener('timeupdate',syncTick);audio.addEventListener('play',syncTick);audio.addEventListener('pause',syncTick);audio.addEventListener('loadedmetadata',syncTick);audio.addEventListener('ended',next);
try{if('mediaSession'in navigator){navigator.mediaSession.setActionHandler('play',()=>offlineMode?toggle():player?.playVideo?.());navigator.mediaSession.setActionHandler('pause',()=>offlineMode?toggle():player?.pauseVideo?.());navigator.mediaSession.setActionHandler('nexttrack',()=>offlineMode?next():document.getElementById('next')?.click());navigator.mediaSession.setActionHandler('previoustrack',()=>offlineMode?prev():document.getElementById('prev')?.click());navigator.mediaSession.setActionHandler('seekto',d=>{if(offlineMode&&Number.isFinite(d.seekTime))audio.currentTime=d.seekTime})}}catch{}
window.addEventListener('online',()=>{if(db)refreshStates().then(paintAll)});window.addEventListener('focus',()=>{if(db)refreshStates().then(paintAll)});document.addEventListener('visibilitychange',()=>{if(!document.hidden&&db)refreshStates().then(paintAll)});
openDB().then(async()=>{await refreshStates();try{await navigator.storage?.persist?.()}catch{};setTimeout(paintAll,300);setInterval(()=>{if(!offlineMode)decorate()},1600)}).catch(e=>{console.warn('Offline DB',e);offlineBtn.disabled=true;offlineBtn.title='Offline úložisko nie je dostupné'});
})();
