// Music search V41 — ONLY search backend changed. UI/player/admin/profile untouched.
const cache=new Map(),RELEASE=41;
const text=n=>typeof n==='string'?n:n?.simpleText||n?.runs?.map(x=>x.text||'').join('')||'';
const clean=s=>String(s||'').replace(/<[^>]*>/g,' ').replace(/&quot;/g,'"').replace(/&#39;|&apos;/g,"'").replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/\s+/g,' ').trim();
const validId=id=>/^[A-Za-z0-9_-]{11}$/.test(id||'');
function initialData(html){for(const marker of ['var ytInitialData =','window["ytInitialData"] =','ytInitialData =']){let p=html.indexOf(marker);if(p<0)continue;p=html.indexOf('{',p+marker.length);if(p<0)continue;let depth=0,quoted=false,escaped=false;for(let i=p;i<html.length;i++){const c=html[i];if(quoted){if(escaped)escaped=false;else if(c==='\\')escaped=true;else if(c==='"')quoted=false}else if(c==='"')quoted=true;else if(c==='{')depth++;else if(c==='}'&&!--depth){try{return JSON.parse(html.slice(p,i+1))}catch{break}}}}throw Error('YouTube metadata missing')}
function collect(data){const out=[],seen=new Set();function walk(node){if(!node||typeof node!=='object')return;const v=node.videoRenderer||node.compactVideoRenderer;if(v?.videoId&&!seen.has(v.videoId)){seen.add(v.videoId);const title=text(v.title);if(title){const d=text(v.lengthText)||text(v.thumbnailOverlays?.find(x=>x.thumbnailOverlayTimeStatusRenderer)?.thumbnailOverlayTimeStatusRenderer?.text),duration=/^\d+(?::\d+){1,2}$/.test(d)?d.split(':').reduce((s,x)=>s*60+Number(x),0):0;out.push({id:'youtube:'+v.videoId,youtubeId:v.videoId,title,artist:text(v.ownerText||v.shortBylineText||v.longBylineText)||'YouTube',duration,artwork:v.thumbnail?.thumbnails?.slice(-1)[0]?.url||'https://i.ytimg.com/vi/'+v.videoId+'/hqdefault.jpg'})}}if(Array.isArray(node))node.forEach(walk);else Object.values(node).forEach(walk)}walk(data);return out.slice(0,40)}
function parseHtml(html,q){const out=[],seen=new Set(),decoded=String(html||'').replace(/\\u0026/g,'&').replace(/&amp;/g,'&').replace(/%3F/g,'?').replace(/%3D/g,'=').replace(/%26/g,'&');const patterns=[/(?:youtube\.com\/watch\?[^\s"'<>]*?v=|youtu\.be\/)([A-Za-z0-9_-]{11})/gi,/"videoId"\s*:\s*"([A-Za-z0-9_-]{11})"/g,/watch%3Fv%3D([A-Za-z0-9_-]{11})/gi];for(const re of patterns){let m;while((m=re.exec(decoded))&&out.length<40){const id=m[1];if(!validId(id)||seen.has(id))continue;seen.add(id);const around=decoded.slice(Math.max(0,m.index-700),Math.min(decoded.length,re.lastIndex+700));const title=clean(around.match(/(?:title|aria-label)=["']([^"']{3,180})["']/i)?.[1])||clean(around.match(/<h3[^>]*>([\s\S]*?)<\/h3>/i)?.[1])||`${q} · YouTube`;out.push({id:'youtube:'+id,youtubeId:id,title,artist:'YouTube',duration:0,artwork:'https://i.ytimg.com/vi/'+id+'/hqdefault.jpg'})}}return out}
async function officialApi(q){const key=process.env.YOUTUBE_API_KEY||process.env.GOOGLE_YOUTUBE_API_KEY||'';if(!key)return[];const r=await fetch('https://www.googleapis.com/youtube/v3/search?part=snippet&type=video&maxResults=40&q='+encodeURIComponent(q)+'&key='+encodeURIComponent(key),{signal:AbortSignal.timeout(7000)});if(!r.ok)throw Error('YT API '+r.status);const d=await r.json();return(d.items||[]).map(x=>({id:'youtube:'+x.id?.videoId,youtubeId:x.id?.videoId,title:x.snippet?.title||'',artist:x.snippet?.channelTitle||'YouTube',duration:0,artwork:x.snippet?.thumbnails?.high?.url||x.snippet?.thumbnails?.medium?.url||''})).filter(x=>validId(x.youtubeId)&&x.title)}
async function direct(q){const all=[];for(const host of ['www.youtube.com','m.youtube.com'])try{const r=await fetch('https://'+host+'/results?search_query='+encodeURIComponent(q)+'&hl=en',{headers:{'User-Agent':'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 Chrome/131.0.0.0 Safari/537.36','Accept-Language':'en-US,en;q=0.9'},signal:AbortSignal.timeout(7000)});if(r.ok)all.push(...collect(initialData(await r.text())))}catch{}return all}
async function fallback(q){const urls=['https://www.google.com/search?tbm=vid&num=50&q='+encodeURIComponent(q+' youtube'),'https://www.bing.com/videos/search?count=50&q='+encodeURIComponent(q+' youtube'),'https://www.google.com/search?num=50&q='+encodeURIComponent(q+' site:youtube.com/watch'),'https://www.bing.com/search?count=50&q='+encodeURIComponent(q+' site:youtube.com/watch')];const settled=await Promise.allSettled(urls.map(u=>fetch(u,{headers:{'User-Agent':'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 Chrome/131.0.0.0 Safari/537.36','Accept-Language':'en-US,en;q=0.9'},signal:AbortSignal.timeout(7000)}).then(async r=>r.ok?parseHtml(await r.text(),q):[])));return settled.flatMap(x=>x.status==='fulfilled'?x.value:[])}
function merge(...groups){const out=[],seen=new Set();for(const group of groups)for(const x of group||[]){if(!validId(x.youtubeId)||seen.has(x.youtubeId))continue;seen.add(x.youtubeId);out.push(x);if(out.length>=40)return out}return out}
export default async function handler(req,res){res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('X-Tesla-Music-Release',String(RELEASE));if(req.method!=='GET')return res.status(405).json({error:'Method not allowed',items:[]});const q=String(new URL(req.url,'https://tesla-waze-piped.vercel.app').searchParams.get('q')||'').trim().slice(0,200);if(!q)return res.status(400).json({error:'Zadaj názov skladby alebo interpreta.',items:[]});const k=q.toLowerCase(),hit=cache.get(k);if(hit&&Date.now()-hit.at<300000)return res.status(200).json(hit.data);try{const [a,b,c]=await Promise.allSettled([officialApi(q),direct(q),fallback(q)]),items=merge(a.status==='fulfilled'?a.value:[],b.status==='fulfilled'?b.value:[],c.status==='fulfilled'?c.value:[]);if(!items.length)throw Error('No results');const data={query:q,items,source:'merged-search',release:RELEASE,anonymous:true};cache.set(k,{at:Date.now(),data});res.setHeader('Cache-Control','public, max-age=0, s-maxage=120');return res.status(200).json(data)}catch(e){console.error('Music search V41:',e.message);return res.status(502).json({error:'Vyhľadávanie je dočasne nedostupné. Skús to znovu.',items:[],release:RELEASE,anonymous:true})}}
