/* Music V41 account/admin layer. Isolated from player/search/map code. */
(()=>{
'use strict';
if(window.musicMemberV41)return;
const API='https://europrojekty-app.vercel.app/api/music';
const SESSION='music:memberSession:v1',USER='music:memberUser:v1';
const KEYS=['teslaMusic:brain:v1','teslaMusic:queue:v1','teslaMusic:searchHistory:v1','teslaMusic:settings:v1'];
let token=localStorage.getItem(SESSION)||'',me=null,syncTimer=0,lastSignature='';
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function style(){if(document.getElementById('musicV41Style'))return;const s=document.createElement('style');s.id='musicV41Style';s.textContent=`
#musicGate{position:fixed;inset:0;z-index:2147483000;background:rgba(10,10,12,.97);display:flex;align-items:center;justify-content:center;padding:20px;font-family:system-ui,-apple-system,sans-serif}.m41card{width:min(430px,100%);background:#17171b;border:1px solid #34343b;border-radius:20px;padding:22px;box-shadow:0 24px 80px rgba(0,0,0,.5);color:#fff}.m41card h2{margin:0 0 8px}.m41muted{opacity:.72;font-size:14px}.m41card input,.m41card select{box-sizing:border-box;width:100%;margin-top:10px;padding:12px 13px;border-radius:12px;border:1px solid #414149;background:#0d0d10;color:#fff;font-size:16px}.m41btn{border:0;border-radius:12px;padding:11px 14px;font-weight:700;cursor:pointer}.m41primary{width:100%;margin-top:12px;background:#fff;color:#111}.m41err{min-height:20px;margin-top:10px;color:#ff8b8b;font-size:14px}.m41account,.m41dots{height:40px;min-width:40px;border-radius:12px;border:1px solid #444;background:#1a1a1f;color:#fff;cursor:pointer}.m41account{padding:0 10px;font-size:12px;max-width:150px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.m41dots{font-size:24px;line-height:1}.m41panel{position:fixed;inset:0;z-index:2147482000;background:rgba(0,0,0,.72);display:flex;align-items:flex-start;justify-content:center;overflow:auto;padding:24px}.m41admin{width:min(900px,100%);background:#151519;color:#fff;border-radius:20px;padding:20px;margin-top:20px}.m41row{display:grid;grid-template-columns:1.5fr 1fr 1fr auto;gap:8px;align-items:center;padding:10px 0;border-bottom:1px solid #303036}.m41row input,.m41row select{width:100%;box-sizing:border-box;background:#0d0d10;color:#fff;border:1px solid #414149;border-radius:9px;padding:9px}.m41actions{display:flex;gap:8px;flex-wrap:wrap}.m41top{display:flex;justify-content:space-between;align-items:center;gap:12px}.m41create{display:grid;grid-template-columns:1.4fr 1fr 1fr 1fr auto;gap:8px;margin:18px 0}.m41create input,.m41create select{min-width:0;background:#0d0d10;color:#fff;border:1px solid #414149;border-radius:9px;padding:10px}.m41pass{font-family:ui-monospace,monospace;background:#0b0b0d;border-radius:8px;padding:8px;margin-top:8px;word-break:break-all}@media(max-width:700px){.m41row,.m41create{grid-template-columns:1fr}.m41admin{margin-top:0}.m41panel{padding:8px}.m41account{display:none}}
`;document.head.appendChild(s)}
async function call(action,data={},auth=true){const h={'content-type':'application/json'};if(auth&&token)h.authorization='Bearer '+token;const r=await fetch(API,{method:'POST',headers:h,body:JSON.stringify({action,...data}),cache:'no-store'});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||('HTTP '+r.status));return d;}
function snapshot(){const out={};for(const k of KEYS){try{out[k]=JSON.parse(localStorage.getItem(k)||'null')}catch{out[k]=null}}return out}
function signature(){return KEYS.map(k=>localStorage.getItem(k)||'').join('|')}
async function saveProfile(force=false){if(!token||!me)return;const sig=signature();if(!force&&sig===lastSignature)return;lastSignature=sig;try{await call('profile.save',{profile:snapshot()})}catch(e){if(/session|prihlásenie|vypršala|deaktivovaný/i.test(String(e.message)))logout(true)}}
function scheduleSave(){clearTimeout(syncTimer);syncTimer=setTimeout(()=>saveProfile(false),1800)}
function applyRemote(p){if(!p||typeof p!=='object')return false;let changed=false;for(const k of KEYS){if(Object.prototype.hasOwnProperty.call(p,k)&&p[k]!==null){localStorage.setItem(k,JSON.stringify(p[k]));changed=true}}return changed}
function gate(){style();let g=document.getElementById('musicGate');if(g)return g;g=document.createElement('div');g.id='musicGate';g.innerHTML=`<div class="m41card"><h2>Music</h2><div class="m41muted">Prihlásenie člena</div><input id="m41email" type="email" autocomplete="username" placeholder="E-mail"><input id="m41pass" type="password" autocomplete="current-password" placeholder="Heslo"><button id="m41login" class="m41btn m41primary">Prihlásiť</button><div id="m41err" class="m41err"></div></div>`;document.body.appendChild(g);g.querySelector('#m41login').onclick=doLogin;g.querySelector('#m41pass').onkeydown=e=>{if(e.key==='Enter')doLogin()};return g}
function hideGate(){document.getElementById('musicGate')?.remove()}
async function doLogin(){const email=document.getElementById('m41email')?.value.trim(),password=document.getElementById('m41pass')?.value||'',err=document.getElementById('m41err'),b=document.getElementById('m41login');if(err)err.textContent='';if(b)b.disabled=true;try{const d=await call('login',{email,password},false);token=d.token;me=d.user;localStorage.setItem(SESSION,token);localStorage.setItem(USER,JSON.stringify(me));const p=await call('profile.get');if(p.profile&&applyRemote(p.profile)){lastSignature=signature();location.reload();return}if(!p.profile)await call('profile.save',{profile:snapshot()});hideGate();installHeader();startSync()}catch(e){if(err)err.textContent=e.message}finally{if(b)b.disabled=false}}
function logout(show=true){saveProfile(true).catch(()=>{});token='';me=null;localStorage.removeItem(SESSION);localStorage.removeItem(USER);document.getElementById('m41dots')?.remove();document.getElementById('m41account')?.remove();if(show)gate()}
function installHeader(){const top=document.querySelector('.top'),q=document.getElementById('q');if(!top||!q||!me)return;if(me.role==='admin'&&!document.getElementById('m41dots')){const d=document.createElement('button');d.id='m41dots';d.className='m41dots';d.textContent='⋮';d.title='Admin';d.onclick=openAdmin;top.insertBefore(d,q)}if(!document.getElementById('m41account')){const a=document.createElement('button');a.id='m41account';a.className='m41account';a.textContent=me.email;a.title='Odhlásiť '+me.email;a.onclick=()=>{if(confirm('Odhlásiť účet '+me.email+'?'))logout(true)};top.appendChild(a)}}
function fmtDate(v){if(!v)return 'bez limitu';const d=new Date(v);return Number.isFinite(d.getTime())?d.toLocaleDateString('sk-SK'):'-'}
async function openAdmin(){if(me?.role!=='admin')return;style();const p=document.createElement('div');p.className='m41panel';p.id='m41panel';p.innerHTML=`<div class="m41admin"><div class="m41top"><div><h2 style="margin:0">Music · Admin</h2><div class="m41muted">Používatelia a platnosť prístupu</div></div><button class="m41btn" id="m41close">✕</button></div><div class="m41create"><input id="m41newEmail" type="email" placeholder="novy@clen.sk"><input id="m41newPass" placeholder="heslo (prázdne = generovať)"><select id="m41newRole"><option value="member">člen</option><option value="admin">admin</option></select><select id="m41newDays"><option value="7">7 dní</option><option value="30">1 mesiac</option><option value="365">1 rok</option><option value="0">bez limitu</option></select><button class="m41btn" id="m41create">Vytvoriť</button></div><div id="m41result" class="m41muted"></div><div id="m41users">Načítavam…</div></div>`;document.body.appendChild(p);p.querySelector('#m41close').onclick=()=>p.remove();p.addEventListener('click',e=>{if(e.target===p)p.remove()});p.querySelector('#m41create').onclick=createMember;await renderUsers()}
async function createMember(){const result=document.getElementById('m41result');try{const email=document.getElementById('m41newEmail').value.trim(),password=document.getElementById('m41newPass').value.trim(),role=document.getElementById('m41newRole').value,durationDays=Number(document.getElementById('m41newDays').value);const d=await call('admin.create',{email,password,role,durationDays});result.innerHTML=`Vytvorený účet: <b>${esc(d.user.email)}</b><div class="m41pass">${esc(d.password)}</div>`;document.getElementById('m41newEmail').value='';document.getElementById('m41newPass').value='';await renderUsers()}catch(e){result.textContent=e.message}}
async function renderUsers(){const box=document.getElementById('m41users');if(!box)return;try{const d=await call('admin.users'),users=d.users||[];box.innerHTML=users.map(u=>`<div class="m41row" data-id="${esc(u.id)}"><input data-email value="${esc(u.email)}"><select data-role><option value="member" ${u.role==='member'?'selected':''}>člen</option><option value="admin" ${u.role==='admin'?'selected':''}>admin</option></select><input data-exp type="date" value="${u.expiresAt?esc(u.expiresAt.slice(0,10)):''}" title="Platnosť do: ${esc(fmtDate(u.expiresAt))}"><div class="m41actions"><button class="m41btn" data-save>Uložiť</button><button class="m41btn" data-pass>Nové heslo</button><button class="m41btn" data-disable>${u.disabled?'Aktivovať':'Vypnúť'}</button></div></div>`).join('')||'Žiadni používatelia.';box.querySelectorAll('.m41row').forEach(row=>{row.querySelector('[data-save]').onclick=()=>editUser(row,false);row.querySelector('[data-pass]').onclick=()=>editUser(row,true);row.querySelector('[data-disable]').onclick=()=>toggleUser(row,users.find(x=>x.id===row.dataset.id))})}catch(e){box.textContent=e.message}}
async function editUser(row,resetPass){const result=document.getElementById('m41result');try{const data={id:row.dataset.id,email:row.querySelector('[data-email]').value.trim(),role:row.querySelector('[data-role]').value,expiresAt:row.querySelector('[data-exp]').value?row.querySelector('[data-exp]').value+'T23:59:59.999Z':null};if(resetPass){const chosen=prompt('Zadaj nové heslo alebo nechaj prázdne pre automatické vygenerovanie:','');if(chosen===null)return;data.password=chosen}const d=await call('admin.update',data);result.innerHTML='Uložené: <b>'+esc(d.user.email)+'</b>'+(d.password?`<div class="m41pass">${esc(d.password)}</div>`:'');if(d.user.id===me.id){me=d.user;localStorage.setItem(USER,JSON.stringify(me));installHeader()}await renderUsers()}catch(e){result.textContent=e.message}}
async function toggleUser(row,u){const result=document.getElementById('m41result');try{if(u.id===me.id&&!u.disabled&&!confirm('Naozaj chceš deaktivovať vlastný admin účet?'))return;await call('admin.update',{id:u.id,disabled:!u.disabled});result.textContent=u.disabled?'Účet aktivovaný.':'Účet deaktivovaný.';await renderUsers()}catch(e){result.textContent=e.message}}
function startSync(){lastSignature=signature();window.addEventListener('tesla-music-trackchange',scheduleSave);window.addEventListener('tesla-youtube-likes-synced',scheduleSave);document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden')saveProfile(false)});window.addEventListener('pagehide',()=>saveProfile(false));setInterval(()=>{if(signature()!==lastSignature)scheduleSave()},12000)}
async function boot(){style();gate();if(!token)return;try{const d=await call('me');me=d.user;localStorage.setItem(USER,JSON.stringify(me));const remote=await call('profile.get');if(remote.profile){const before=signature();applyRemote(remote.profile);const after=signature();lastSignature=after;if(before!==after){location.reload();return}}else await call('profile.save',{profile:snapshot()});hideGate();installHeader();startSync()}catch{logout(true)}}
window.musicMemberV41=Object.freeze({version:41,logout,state:()=>({user:me,loggedIn:!!me,admin:me?.role==='admin'})});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
